In [315]:
# chavez & coombs 
# 1S(v1).ipynb
# 2020-08-27
# data managagement for deltek "1S" data save as U:\AP2 Regular & OT Hours for Adv by CCC_#505ap.xlsx

In [316]:
# import modules
import pandas
import os
import sys
import gc
import datetime

In [317]:
# current working directory
print(os.getcwd())

\\ain2\dfsroot\userdata48\willitc0\Data

In [318]:
# list directories and files
os.listdir()

['$RECYCLE.BIN',
 '.ipynb_checkpoints',
 '.Rhistory',
 '1S(v1).ipynb',
 'AP2 Regular & OT Hours for Adv by CCC_#505ap-modified.csv',
 'Cleaned',
 'cognos_1s_management(v1).ipynb',
 'cognos_data_management(v1).ipynb',
 'cognos_data_management(v1.1).ipynb',
 'cognos_data_management(v1.2).ipynb',
 'cognos_data_management(v1.3).ipynb',
 'cognos_data_management(v2).ipynb',
 'cognos_data_management(v2.1).ipynb',
 'cognos_data_management(v3).ipynb',
 'cognos_data_management_13976(v3).ipynb',
 'cognos_data_management_1S(v3).ipynb',
 'Custom Office Templates',
 'CV-William T. Coombs (8 April 2018).pdf',
 'date to intervals.ipynb',
 'desktop.ini',
 'IE',
 'import_this_data-modified.csv',
 'logoff.txt',
 'logon.txt',
 'movehomelog.txt',
 'My Music',
 'My Pictures',
 'My Videos',
 'picnicapp (14 June 2018).pdf',
 'prelogon.txt',
 'quiz_data.ipynb',
 'R',
 'RECYCLER',
 'Redacted',
 'RegSandRV2ExceptionLog.txt',
 'RegSandRV2Log.txt',
 'Remote Assistance Logs',
 'simulate data.ipynb',
 'suggestions-wtc.docx',
 'suggestions-wtc.pdf',
 'Untitled Folder',
 'vitality2-1-wtc.docx']

In [319]:
# read data
# df = pd.read_csv (r'Path where the CSV file is stored\File name.csv')
data = pandas.read_excel (r'U:\AP2 Regular & OT Hours for Adv by CCC_#505ap.xlsx')

In [320]:
# Pandas has the following data types:
#    object
#    int64
#    float64
#    bool
#    datetime64
#    timedelta[ns]
#    category

In [321]:
# check metadata
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595850 entries, 0 to 595849
Data columns (total 23 columns):
User                 595850 non-null object
User Id              595850 non-null object
Work Date            595850 non-null datetime64[ns]
Month                595850 non-null datetime64[ns]
Description          595850 non-null object
REF ID               595850 non-null object
CLIN                 595850 non-null object
WBS                  9573 non-null object
TASK                 308391 non-null object
TPID                 595850 non-null object
ProjNo               595850 non-null object
WB2                  595832 non-null object
Project Id           595850 non-null object
Pay Type             595850 non-null object
Corporation          595850 non-null object
Company Name         595850 non-null object
Approver             595850 non-null object
Status               595850 non-null object
Straight             595850 non-null float64
Overtime             595850 non-null float64
Total                595850 non-null float64
Date Time Entered    595850 non-null datetime64[ns]
Org Id               595850 non-null object
dtypes: datetime64[ns](3), float64(3), object(17)
memory usage: 104.6+ MB

In [322]:
# trim data
df = pandas.DataFrame(data, columns= ['User','Work Date', 'Description', 'CLIN', 'WB2', 'TPID', 'Straight', 'Overtime', 'Total'])
df.head(5)

,User,Work Date,Description,CLIN,WB2,TPID,Straight,Overtime,Total
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
3,"THOMPSON, MORRIS R",2017-08-10,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
4,"THOMPSON, MORRIS R",2017-08-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00

In [323]:
# rename WB2 to WBS
df = df.rename(columns={'WB2':'WBS'})
df.head(5)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
3,"THOMPSON, MORRIS R",2017-08-10,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
4,"THOMPSON, MORRIS R",2017-08-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00

In [324]:
# check metadata
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595850 entries, 0 to 595849
Data columns (total 9 columns):
User           595850 non-null object
Work Date      595850 non-null datetime64[ns]
Description    595850 non-null object
CLIN           595850 non-null object
WBS            595832 non-null object
TPID           595850 non-null object
Straight       595850 non-null float64
Overtime       595850 non-null float64
Total          595850 non-null float64
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 40.9+ MB

In [325]:
# check dataframe dimensions (rows x columns)
df.shape

(595850, 9)

In [326]:
# delete original dataframe to free up memory
del[data]

In [327]:
gc.collect()

596192

In [328]:
# identify 1SAP2, ...
df['ID'] = df.TPID.str.split(".", expand=True,)[0]
df.head(3)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,1SAP2
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2

In [329]:
# what are the id?
df['ID'].value_counts()

1SAP2    595018
1SFSP       646
1SFN5        63
1SCB3        46
1SCA2        26
1SCN5        22
1SFA2         9
1SFB3         6
1SFB4         5
1SXN5         5
1S10P         3
1SF01         1
Name: ID, dtype: int64

In [330]:
# format float64 datatype
# round floating numbers to two decimal places in python pandas 
pandas.options.display.float_format = '{:.2f}'.format

In [331]:
# check data types
df.dtypes

User                   object
Work Date      datetime64[ns]
Description            object
CLIN                   object
WBS                    object
TPID                   object
Straight              float64
Overtime              float64
Total                 float64
ID                     object
dtype: object

In [332]:
df.head(3)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,1SAP2
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2

In [333]:
# create option year column based on work date
# df1['date'] = pandas.to_datetime(df1['date'])
oy0_mask = (df['Work Date']>='2009-08-03') & (df['Work Date']<='2010-08-02')
oy1_mask = (df['Work Date']>='2010-08-03') & (df['Work Date']<='2011-08-02')
oy2_mask = (df['Work Date']>='2011-08-03') & (df['Work Date']<='2012-08-02')
oy3_mask = (df['Work Date']>='2012-08-03') & (df['Work Date']<='2013-08-02')
oy4_mask = (df['Work Date']>='2013-08-03') & (df['Work Date']<='2014-08-02')
oy5_mask = (df['Work Date']>='2014-08-03') & (df['Work Date']<='2015-08-02')
oy6_mask = (df['Work Date']>='2015-08-03') & (df['Work Date']<='2016-08-02')
oy7_mask = (df['Work Date']>='2016-08-03') & (df['Work Date']<='2017-08-02')
oy8_mask = (df['Work Date']>='2017-08-03') & (df['Work Date']<='2018-08-02')
oy9_mask = (df['Work Date']>='2018-08-03') & (df['Work Date']<='2019-08-02')
bridge_mask = (df['Work Date']>='2019-08-03')

df.loc[oy0_mask, 'OptYr'] = 'OY0'
df.loc[oy1_mask, 'OptYr'] = 'OY1'
df.loc[oy2_mask, 'OptYr'] = 'OY2'
df.loc[oy3_mask, 'OptYr'] = 'OY3'
df.loc[oy4_mask, 'OptYr'] = 'OY4'
df.loc[oy5_mask, 'OptYr'] = 'OY5'
df.loc[oy6_mask, 'OptYr'] = 'OY6'
df.loc[oy7_mask, 'OptYr'] = 'OY7'
df.loc[oy8_mask, 'OptYr'] = 'OY8'
df.loc[oy9_mask, 'OptYr'] = 'OY9'
df.loc[bridge_mask, 'OptYr'] = 'OY.'

df

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,1SAP2,OY7
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
3,"THOMPSON, MORRIS R",2017-08-10,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
4,"THOMPSON, MORRIS R",2017-08-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
5,"THOMPSON, MORRIS R",2017-09-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
6,"THOMPSON, MORRIS R",2017-09-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
7,"THOMPSON, MORRIS R",2017-09-21,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
8,"THOMPSON, MORRIS R",2017-09-25,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
9,"THOMPSON, MORRIS R",2017-10-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
10,"THOMPSON, MORRIS R",2017-10-27,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
11,"THOMPSON, MORRIS R",2017-10-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
12,"THOMPSON, MORRIS R",2017-11-02,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
13,"THOMPSON, MORRIS R",2017-11-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
14,"THOMPSON, MORRIS R",2017-11-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
15,"THOMPSON, MORRIS R",2017-11-17,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
16,"THOMPSON, MORRIS R",2017-11-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
17,"THOMPSON, MORRIS R",2017-11-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
18,"THOMPSON, MORRIS R",2017-11-29,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
19,"THOMPSON, MORRIS R",2017-12-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
20,"THOMPSON, MORRIS R",2018-01-16,Asset Management,8400,514,1SAP2.C.8400.514,4.00,0.00,4.00,1SAP2,OY8
21,"THOMPSON, MORRIS R",2018-01-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
22,"THOMPSON, MORRIS R",2018-02-12,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
23,"THOMPSON, MORRIS R",2018-02-20,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00,1SAP2,OY8
24,"THOMPSON, MORRIS R",2018-02-23,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00,1SAP2,OY8
25,"THOMPSON, MORRIS R",2018-02-23,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8
26,"THOMPSON, MORRIS R",2018-03-05,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
27,"THOMPSON, MORRIS R",2018-03-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
28,"THOMPSON, MORRIS R",2018-03-07,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8
29,"THOMPSON, MORRIS R",2018-03-16,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8
...,...,...,...,...,...,...,...,...,...,...,...
595820,"Simmons, Kenneth",2017-05-02,D Mission Support,7300,683,1SAP2.C.7300.683,9.00,0.00,9.00,1SAP2,OY7
595821,"Simmons, Kenneth",2017-05-09,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595822,"Simmons, Kenneth",2017-05-18,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595823,"Simmons, Kenneth",2017-06-27,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7
595824,"Simmons, Kenneth",2017-06-28,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595825,"Simmons, Kenneth",2017-07-03,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50,1SAP2,OY7
595826,"Simmons, Kenneth",2017-07-05,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00,1SAP2,OY7
595827,"Simmons, Kenneth",2017-07-08,D Mission Support,7300,683,1SAP2.C.7300.683,4.50,0.00,4.50,1SAP2,OY7
595828,"Simmons, Kenneth",2017-03-29,D Mission Support,7300,683,1SAP2.C.7300.683,7.50,0.00,7.50,1SAP2,OY7
595829,"Simmons, Kenneth",2017-04-06,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00,1SAP2,OY7
595830,"Simmons, Kenneth",2017-04-19,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7
595831,"Simmons, Kenneth",2017-04-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595832,"Simmons, Kenneth",2017-04-26,D Mission Support,7300,683,1SAP2.C.7300.683,9.50,0.00,9.50,1SAP2,OY7
595833,"Simmons, Kenneth",2017-05-05,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595834,"Simmons, Kenneth",2017-05-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595835,"Simmons, Kenneth",2017-05-31,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7
595836,"Simmons, Kenneth",2017-06-06,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7
595837,"Simmons, Kenneth",2017-06-18,D Mission Support,7300,683,1SAP2.C.7300.683,13.00,0.00,13.00,1SAP2,OY7
595838,"Simmons, Kenneth",2017-06-21,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595839,"Simmons, Kenneth",2017-07-10,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595840,"Simmons, Kenneth",2017-07-13,D Mission Support,7300,683,1SAP2.C.7300.683,3.50,0.00,3.50,1SAP2,OY7
595841,"Simmons, Kenneth",2017-03-20,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595842,"Simmons, Kenneth",2017-03-23,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595843,"Simmons, Kenneth",2017-03-27,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00,1SAP2,OY7
595844,"Simmons, Kenneth",2017-04-17,D Mission Support,7300,683,1SAP2.C.7300.683,6.00,0.00,6.00,1SAP2,OY7
595845,"Simmons, Kenneth",2017-05-07,D Mission Support,7300,683,1SAP2.C.7300.683,14.00,0.00,14.00,1SAP2,OY7
595846,"Simmons, Kenneth",2017-05-10,D Mission Support,7300,683,1SAP2.C.7300.683,11.50,0.00,11.50,1SAP2,OY7
595847,"Simmons, Kenneth",2017-06-13,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7
595848,"Simmons, Kenneth",2017-07-06,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00,1SAP2,OY7
595849,"Simmons, Kenneth",2017-07-19,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50,1SAP2,OY7

In [334]:
# check data
df[df['OptYr'] == 'OY0']

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr]
Index: []

In [335]:
# check data
df[df['OptYr'] == 'OY1']

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr]
Index: []

In [336]:
# check data
df[df['OptYr'] == 'OY2']

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr]
Index: []

In [337]:
# check data
df[df['OptYr'] == 'OY3']

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr]
Index: []

In [338]:
# check data
df[df['OptYr'] == 'OY4']

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr]
Index: []

In [339]:
# check data
df[df['OptYr'] == 'OY5']

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr]
Index: []

In [340]:
# check data
df[df['OptYr'] == 'OY6']

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr]
Index: []

In [341]:
# check data
df[df['OptYr'] == 'OY7']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,1SAP2,OY7
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
56,"THOMPSON, MORRIS R",2017-07-11,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7
57,"THOMPSON, MORRIS R",2017-07-18,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7
58,"THOMPSON, MORRIS R",2017-08-01,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
127,"THOMPSON, MORRIS R",2017-07-17,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7
128,"THOMPSON, MORRIS R",2017-07-19,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
129,"THOMPSON, MORRIS R",2017-07-20,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,1SAP2,OY7
190,"THOMPSON, MORRIS R",2017-07-13,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7
256,"THOMPSON, MORRIS R",2017-07-12,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7
257,"THOMPSON, MORRIS R",2017-07-27,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
330,"THOMPSON, MORRIS R",2017-07-21,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
397,"THOMPSON, MORRIS R",2017-07-14,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7
398,"THOMPSON, MORRIS R",2017-07-20,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
399,"THOMPSON, MORRIS R",2017-07-25,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
400,"THOMPSON, MORRIS R",2017-07-26,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
401,"THOMPSON, MORRIS R",2017-08-02,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
477,"THOMPSON, MORRIS R",2017-07-10,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
478,"THOMPSON, MORRIS R",2017-07-28,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
875,"LOVELACE, TAMEKA N",2017-03-20,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00,1SAP2,OY7
876,"LOVELACE, TAMEKA N",2017-03-22,Site L,7900,000,1SAP2.C.7900.000,0.00,4.00,4.00,1SAP2,OY7
877,"LOVELACE, TAMEKA N",2017-03-23,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00,1SAP2,OY7
878,"LOVELACE, TAMEKA N",2017-04-05,Site L,7900,000,1SAP2.C.7900.000,0.00,4.00,4.00,1SAP2,OY7
879,"LOVELACE, TAMEKA N",2017-04-10,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00,1SAP2,OY7
880,"LOVELACE, TAMEKA N",2017-04-19,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00,1SAP2,OY7
881,"LOVELACE, TAMEKA N",2017-05-04,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00,1SAP2,OY7
882,"LOVELACE, TAMEKA N",2017-05-09,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00,1SAP2,OY7
883,"LOVELACE, TAMEKA N",2017-05-12,Site L,7900,000,1SAP2.C.7900.000,0.00,4.00,4.00,1SAP2,OY7
884,"LOVELACE, TAMEKA N",2017-05-24,Site L,7900,000,1SAP2.C.7900.000,0.00,4.00,4.00,1SAP2,OY7
...,...,...,...,...,...,...,...,...,...,...,...
595820,"Simmons, Kenneth",2017-05-02,D Mission Support,7300,683,1SAP2.C.7300.683,9.00,0.00,9.00,1SAP2,OY7
595821,"Simmons, Kenneth",2017-05-09,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595822,"Simmons, Kenneth",2017-05-18,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595823,"Simmons, Kenneth",2017-06-27,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7
595824,"Simmons, Kenneth",2017-06-28,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595825,"Simmons, Kenneth",2017-07-03,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50,1SAP2,OY7
595826,"Simmons, Kenneth",2017-07-05,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00,1SAP2,OY7
595827,"Simmons, Kenneth",2017-07-08,D Mission Support,7300,683,1SAP2.C.7300.683,4.50,0.00,4.50,1SAP2,OY7
595828,"Simmons, Kenneth",2017-03-29,D Mission Support,7300,683,1SAP2.C.7300.683,7.50,0.00,7.50,1SAP2,OY7
595829,"Simmons, Kenneth",2017-04-06,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00,1SAP2,OY7
595830,"Simmons, Kenneth",2017-04-19,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7
595831,"Simmons, Kenneth",2017-04-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595832,"Simmons, Kenneth",2017-04-26,D Mission Support,7300,683,1SAP2.C.7300.683,9.50,0.00,9.50,1SAP2,OY7
595833,"Simmons, Kenneth",2017-05-05,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595834,"Simmons, Kenneth",2017-05-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595835,"Simmons, Kenneth",2017-05-31,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7
595836,"Simmons, Kenneth",2017-06-06,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7
595837,"Simmons, Kenneth",2017-06-18,D Mission Support,7300,683,1SAP2.C.7300.683,13.00,0.00,13.00,1SAP2,OY7
595838,"Simmons, Kenneth",2017-06-21,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595839,"Simmons, Kenneth",2017-07-10,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595840,"Simmons, Kenneth",2017-07-13,D Mission Support,7300,683,1SAP2.C.7300.683,3.50,0.00,3.50,1SAP2,OY7
595841,"Simmons, Kenneth",2017-03-20,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595842,"Simmons, Kenneth",2017-03-23,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7
595843,"Simmons, Kenneth",2017-03-27,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00,1SAP2,OY7
595844,"Simmons, Kenneth",2017-04-17,D Mission Support,7300,683,1SAP2.C.7300.683,6.00,0.00,6.00,1SAP2,OY7
595845,"Simmons, Kenneth",2017-05-07,D Mission Support,7300,683,1SAP2.C.7300.683,14.00,0.00,14.00,1SAP2,OY7
595846,"Simmons, Kenneth",2017-05-10,D Mission Support,7300,683,1SAP2.C.7300.683,11.50,0.00,11.50,1SAP2,OY7
595847,"Simmons, Kenneth",2017-06-13,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7
595848,"Simmons, Kenneth",2017-07-06,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00,1SAP2,OY7
595849,"Simmons, Kenneth",2017-07-19,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50,1SAP2,OY7

In [342]:
# check data
df[df['OptYr'] == 'OY8']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr
3,"THOMPSON, MORRIS R",2017-08-10,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
4,"THOMPSON, MORRIS R",2017-08-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
5,"THOMPSON, MORRIS R",2017-09-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
6,"THOMPSON, MORRIS R",2017-09-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
7,"THOMPSON, MORRIS R",2017-09-21,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
8,"THOMPSON, MORRIS R",2017-09-25,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
9,"THOMPSON, MORRIS R",2017-10-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
10,"THOMPSON, MORRIS R",2017-10-27,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
11,"THOMPSON, MORRIS R",2017-10-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
12,"THOMPSON, MORRIS R",2017-11-02,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
13,"THOMPSON, MORRIS R",2017-11-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
14,"THOMPSON, MORRIS R",2017-11-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
15,"THOMPSON, MORRIS R",2017-11-17,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
16,"THOMPSON, MORRIS R",2017-11-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
17,"THOMPSON, MORRIS R",2017-11-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
18,"THOMPSON, MORRIS R",2017-11-29,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
19,"THOMPSON, MORRIS R",2017-12-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
20,"THOMPSON, MORRIS R",2018-01-16,Asset Management,8400,514,1SAP2.C.8400.514,4.00,0.00,4.00,1SAP2,OY8
21,"THOMPSON, MORRIS R",2018-01-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
22,"THOMPSON, MORRIS R",2018-02-12,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
23,"THOMPSON, MORRIS R",2018-02-20,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00,1SAP2,OY8
24,"THOMPSON, MORRIS R",2018-02-23,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00,1SAP2,OY8
25,"THOMPSON, MORRIS R",2018-02-23,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8
26,"THOMPSON, MORRIS R",2018-03-05,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
27,"THOMPSON, MORRIS R",2018-03-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8
28,"THOMPSON, MORRIS R",2018-03-07,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8
29,"THOMPSON, MORRIS R",2018-03-16,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8
30,"THOMPSON, MORRIS R",2018-03-23,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,7.50,0.00,7.50,1SAP2,OY8
31,"THOMPSON, MORRIS R",2018-03-27,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8
32,"THOMPSON, MORRIS R",2018-05-16,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8
...,...,...,...,...,...,...,...,...,...,...,...
595662,"Holbrook, Michael",2017-08-29,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00,1SAP2,OY8
595663,"Holbrook, Michael",2017-09-01,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00,1SAP2,OY8
595664,"Holbrook, Michael",2017-09-04,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00,1SAP2,OY8
595665,"Holbrook, Michael",2017-09-06,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00,1SAP2,OY8
595666,"Holbrook, Michael",2017-09-07,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595667,"Holbrook, Michael",2017-09-14,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00,1SAP2,OY8
595668,"Holbrook, Michael",2017-10-03,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595669,"Holbrook, Michael",2017-10-04,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595670,"Holbrook, Michael",2017-10-06,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,5.00,0.00,5.00,1SAP2,OY8
595671,"Holbrook, Michael",2017-10-17,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595672,"Holbrook, Michael",2017-10-26,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595673,"Holbrook, Michael",2017-11-09,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595683,"Holbrook, Michael",2017-08-11,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,7.00,0.00,7.00,1SAP2,OY8
595684,"Holbrook, Michael",2017-08-21,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595685,"Holbrook, Michael",2017-08-28,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00,1SAP2,OY8
595686,"Holbrook, Michael",2017-08-31,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00,1SAP2,OY8
595687,"Holbrook, Michael",2017-09-05,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00,1SAP2,OY8
595688,"Holbrook, Michael",2017-09-21,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595689,"Holbrook, Michael",2017-10-02,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.50,0.00,8.50,1SAP2,OY8
595690,"Holbrook, Michael",2017-10-11,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,9.00,0.00,9.00,1SAP2,OY8
595691,"Holbrook, Michael",2017-11-03,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,7.00,0.00,7.00,1SAP2,OY8
595692,"Holbrook, Michael",2017-11-07,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595693,"Holbrook, Michael",2017-11-15,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595707,"Holbrook, Michael",2017-08-03,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,10.00,0.00,10.00,1SAP2,OY8
595708,"Holbrook, Michael",2017-08-15,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,14.50,0.00,14.50,1SAP2,OY8
595709,"Holbrook, Michael",2017-09-11,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595710,"Holbrook, Michael",2017-09-13,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00,1SAP2,OY8
595711,"Holbrook, Michael",2017-09-26,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,7.00,0.00,7.00,1SAP2,OY8
595712,"Holbrook, Michael",2017-10-13,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8
595713,"Holbrook, Michael",2017-10-23,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00,1SAP2,OY8

In [343]:
# check data
df[df['OptYr'] == 'OY9']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr
35,"THOMPSON, MORRIS R",2018-08-06,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
36,"THOMPSON, MORRIS R",2018-08-20,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50,1SAP2,OY9
37,"THOMPSON, MORRIS R",2018-08-22,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
38,"THOMPSON, MORRIS R",2018-08-30,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
39,"THOMPSON, MORRIS R",2018-09-06,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
40,"THOMPSON, MORRIS R",2018-09-26,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
41,"THOMPSON, MORRIS R",2018-10-10,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
42,"THOMPSON, MORRIS R",2018-10-15,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
43,"THOMPSON, MORRIS R",2019-01-07,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
44,"THOMPSON, MORRIS R",2019-02-22,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
45,"THOMPSON, MORRIS R",2019-03-18,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50,1SAP2,OY9
46,"THOMPSON, MORRIS R",2019-03-26,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50,1SAP2,OY9
47,"THOMPSON, MORRIS R",2019-04-18,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50,1SAP2,OY9
48,"THOMPSON, MORRIS R",2019-04-22,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50,1SAP2,OY9
49,"THOMPSON, MORRIS R",2019-05-10,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,6.00,0.00,6.00,1SAP2,OY9
50,"THOMPSON, MORRIS R",2019-05-20,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50,1SAP2,OY9
51,"THOMPSON, MORRIS R",2019-06-07,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,5.50,0.00,5.50,1SAP2,OY9
52,"THOMPSON, MORRIS R",2019-06-20,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,9.00,0.00,9.00,1SAP2,OY9
53,"THOMPSON, MORRIS R",2019-06-26,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,9.00,0.00,9.00,1SAP2,OY9
54,"THOMPSON, MORRIS R",2019-07-15,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,9.00,0.00,9.00,1SAP2,OY9
55,"THOMPSON, MORRIS R",2019-07-23,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,9.00,0.00,9.00,1SAP2,OY9
100,"THOMPSON, MORRIS R",2018-08-21,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
101,"THOMPSON, MORRIS R",2018-09-17,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,9.50,0.00,9.50,1SAP2,OY9
102,"THOMPSON, MORRIS R",2018-09-18,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
103,"THOMPSON, MORRIS R",2018-10-25,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
104,"THOMPSON, MORRIS R",2018-11-15,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
105,"THOMPSON, MORRIS R",2018-11-30,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,7.00,0.00,7.00,1SAP2,OY9
106,"THOMPSON, MORRIS R",2018-12-10,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
107,"THOMPSON, MORRIS R",2018-12-27,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00,1SAP2,OY9
108,"THOMPSON, MORRIS R",2019-01-11,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,7.00,0.00,7.00,1SAP2,OY9
...,...,...,...,...,...,...,...,...,...,...,...
595349,"Stokes, Duane",2019-02-28,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,11.00,0.00,11.00,1SAP2,OY9
595350,"Stokes, Duane",2019-03-04,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00,1SAP2,OY9
595351,"Stokes, Duane",2019-03-18,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,9.50,0.00,9.50,1SAP2,OY9
595352,"Stokes, Duane",2019-04-18,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,13.00,0.00,13.00,1SAP2,OY9
595353,"Stokes, Duane",2019-05-03,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00,1SAP2,OY9
595354,"Stokes, Duane",2019-06-13,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,11.50,0.00,11.50,1SAP2,OY9
595355,"Stokes, Duane",2019-06-24,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00,1SAP2,OY9
595356,"Stokes, Duane",2019-07-16,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00,1SAP2,OY9
595357,"Stokes, Duane",2019-07-23,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,12.50,0.00,12.50,1SAP2,OY9
595358,"Stokes, Duane",2019-07-29,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,7.00,0.00,7.00,1SAP2,OY9
595359,"Stokes, Duane",2019-08-01,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,9.00,0.00,9.00,1SAP2,OY9
595396,"Stokes, Duane",2018-08-23,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00,1SAP2,OY9
595397,"Stokes, Duane",2018-10-02,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,9.50,0.00,9.50,1SAP2,OY9
595398,"Stokes, Duane",2018-10-09,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,12.00,0.00,12.00,1SAP2,OY9
595399,"Stokes, Duane",2018-10-26,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,8.00,0.00,8.00,1SAP2,OY9
595400,"Stokes, Duane",2018-12-07,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,7.00,0.00,7.00,1SAP2,OY9
595401,"Stokes, Duane",2018-12-11,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,7.50,0.00,7.50,1SAP2,OY9
595402,"Stokes, Duane",2018-12-21,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,11.00,0.00,11.00,1SAP2,OY9
595403,"Stokes, Duane",2019-02-12,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,11.00,0.00,11.00,1SAP2,OY9
595404,"Stokes, Duane",2019-02-14,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,8.00,0.00,8.00,1SAP2,OY9
595405,"Stokes, Duane",2019-04-24,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,13.00,0.00,13.00,1SAP2,OY9
595406,"Stokes, Duane",2019-05-20,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,4.50,0.00,4.50,1SAP2,OY9
595407,"Stokes, Duane",2019-05-31,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,12.00,0.00,12.00,1SAP2,OY9
595408,"Stokes, Duane",2019-06-04,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,8.00,0.00,8.00,1SAP2,OY9
595409,"Stokes, Duane",2019-06-11,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,9.00,0.00,9.00,1SAP2,OY9
595410,"Stokes, Duane",2019-06-17,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00,1SAP2,OY9
595411,"Stokes, Duane",2019-07-02,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,11.00,0.00,11.00,1SAP2,OY9
595412,"Stokes, Duane",2019-07-04,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,0.00,0.00,0.00,1SAP2,OY9
595413,"Stokes, Duane",2019-07-08,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,7.00,0.00,7.00,1SAP2,OY9
595414,"Stokes, Duane",2019-07-30,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00,1SAP2,OY9

In [344]:
# check data
df[df['OptYr'] == 'OY.']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr
1119,"LOVELACE, TAMEKA N",2019-08-06,Site L,9900,000,1SAP2.C.9900.000,0.00,0.00,0.00,1SAP2,OY.
1811,"LOVELACE, TAMEKA N",2019-08-05,Site L,9900,000,1SAP2.C.9900.000,0.00,0.00,0.00,1SAP2,OY.
11276,"TIMMONS, CARL A",2019-08-08,FS Installer,9420,000,1SAP2.P.9420.000.4926393,-4.00,0.00,-4.00,1SAP2,OY.
11477,"TIMMONS, CARL A",2019-08-08,FS Installer,9420,000,1SAP2.P.9420.000.4926393,4.00,0.00,4.00,1SAP2,OY.
11584,"TIMMONS, CARL A",2019-08-12,FS Installer,9420,000,1SAP2.P.9420.000.5364379,0.00,0.00,0.00,1SAP2,OY.
31417,"SHINGLES, VELGAMON C",2019-08-06,FS Installer,9420,000,1SAP2.P.9420.000.5259260,0.00,0.00,0.00,1SAP2,OY.
31614,"SHINGLES, VELGAMON C",2019-08-05,FS Installer,9420,000,1SAP2.P.9420.000.5259260,0.00,0.00,0.00,1SAP2,OY.
31754,"SHINGLES, VELGAMON C",2019-08-07,FS Installer,9420,000,1SAP2.P.9420.000.5259260,0.00,0.00,0.00,1SAP2,OY.
36700,"MAYS, BERNADETTE",2019-08-19,Switch Tech (Local),9440,225,1SAP2.C.9440.225,0.00,0.00,0.00,1SAP2,OY.
47470,"MULLINS, JAMES D",2019-08-07,FS Installer,9420,000,1SAP2.P.9420.000.5473263,0.00,0.00,0.00,1SAP2,OY.
47670,"MULLINS, JAMES D",2019-08-07,FS Installer,9420,000,1SAP2.P.9420.000.5257101,0.00,0.00,0.00,1SAP2,OY.
47742,"MULLINS, JAMES D",2019-08-06,FS Installer,9420,000,1SAP2.P.9420.000.5473263,0.00,0.00,0.00,1SAP2,OY.
47743,"MULLINS, JAMES D",2019-08-08,FS Installer,9420,000,1SAP2.P.9420.000.5257101,0.00,0.00,0.00,1SAP2,OY.
47859,"MULLINS, JAMES D",2019-08-09,FS Installer,9420,000,1SAP2.P.9420.000.5257101,0.00,0.00,0.00,1SAP2,OY.
47916,"MULLINS, JAMES D",2019-08-05,FS Installer,9420,000,1SAP2.P.9420.000.5257101,0.00,0.00,0.00,1SAP2,OY.
68445,"BUCKMON, JOSEPH",2019-09-04,CD&D (Local),9440,215,1SAP2.C.9440.215,0.00,0.00,0.00,1SAP2,OY.
70200,"JONES, BILLIE H",2019-08-12,Proj Mgmt (Local),9440,415,1SAP2.C.9440.415,0.00,0.00,0.00,1SAP2,OY.
74071,"MAY, PORTIAH A",2019-08-05,PMO CLIN 9105,9105,000,1SAP2.C.9105.000,0.00,0.00,0.00,1SAP2,OY.
75715,"MAY, PORTIAH A",2019-08-05,PMO CLIN 9103,9103,000,1SAP2.C.9103.000,0.00,0.00,0.00,1SAP2,OY.
75986,"MAY, PORTIAH A",2019-08-05,PMO CLIN 9104,9104,000,1SAP2.C.9104.000,0.00,0.00,0.00,1SAP2,OY.
89221,"EDWARDS, REGINA",2019-08-07,Telephony,9400,517,1SAP2.C.9400.517,0.00,0.00,0.00,1SAP2,OY.
89375,"EDWARDS, REGINA",2019-08-08,Telephony,9400,517,1SAP2.C.9400.517,0.00,0.00,0.00,1SAP2,OY.
89432,"EDWARDS, REGINA",2019-08-06,Telephony,9400,517,1SAP2.C.9400.517,0.00,0.00,0.00,1SAP2,OY.
89433,"EDWARDS, REGINA",2019-08-09,Telephony,9400,517,1SAP2.C.9400.517,0.00,0.00,0.00,1SAP2,OY.
102593,"PERKINS, WILLIAM F",2019-10-15,Installer (Local),9440,815,1SAP2.C.9440.815,0.00,0.00,0.00,1SAP2,OY.
106559,"DEHN, ALBERT W",2019-08-05,FS Installer,9420,000,1SAP2.P.9420.000.4926393,8.00,0.00,8.00,1SAP2,OY.
106645,"DEHN, ALBERT W",2019-08-12,FS Installer,9420,000,1SAP2.P.9420.000.5364379,-8.00,0.00,-8.00,1SAP2,OY.
106808,"DEHN, ALBERT W",2019-08-07,FS Installer,9420,000,1SAP2.P.9420.000.4926393,8.00,0.00,8.00,1SAP2,OY.
106809,"DEHN, ALBERT W",2019-08-12,FS Installer,9420,000,1SAP2.P.9420.000.5364379,8.00,0.00,8.00,1SAP2,OY.
106903,"DEHN, ALBERT W",2019-08-05,FS Installer,9420,000,1SAP2.P.9420.000.4926393,-8.00,0.00,-8.00,1SAP2,OY.
...,...,...,...,...,...,...,...,...,...,...,...
544982,"Parker, Derrick",2019-08-08,FS Installer,9420,000,1SAP2.P.9420.000.4926393,-4.00,0.00,-4.00,1SAP2,OY.
545010,"Parker, Derrick",2019-08-09,FS Installer,9420,000,1SAP2.P.9420.000.4926393,-8.00,0.00,-8.00,1SAP2,OY.
545601,"Bellamy, Willie",2019-08-05,FS Installer,9420,000,1SAP2.P.9420.000.5066612,0.00,0.00,0.00,1SAP2,OY.
546861,"Sabur, Ali",2019-10-30,FS Installer,9420,000,1SAP2.P.9420.000.5066612,10.00,0.00,10.00,1SAP2,OY.
546862,"Sabur, Ali",2019-10-21,FS Installer,9420,000,1SAP2.P.9420.000.5328120,10.00,0.00,10.00,1SAP2,OY.
546863,"Sabur, Ali",2019-10-31,FS Installer,9420,000,1SAP2.P.9420.000.5066612,0.00,0.00,0.00,1SAP2,OY.
546864,"Sabur, Ali",2019-10-17,FS Installer,9420,000,1SAP2.P.9420.000.5328120,-10.00,0.00,-10.00,1SAP2,OY.
546865,"Sabur, Ali",2019-10-29,FS Installer,9420,000,1SAP2.P.9420.000.5066612,4.00,0.00,4.00,1SAP2,OY.
546866,"Sabur, Ali",2019-10-31,FS Installer,9420,000,1SAP2.P.9420.000.5066612,10.00,0.00,10.00,1SAP2,OY.
546867,"Sabur, Ali",2019-11-04,FS Installer,9420,000,1SAP2.P.9420.000.5066612,8.00,0.00,8.00,1SAP2,OY.
546868,"Sabur, Ali",2019-10-21,FS Installer,9420,000,1SAP2.P.9420.000.5328120,-10.00,0.00,-10.00,1SAP2,OY.
546869,"Sabur, Ali",2019-11-04,FS Installer,9420,000,1SAP2.P.9420.000.5066612,-8.00,0.00,-8.00,1SAP2,OY.
546870,"Sabur, Ali",2019-10-29,FS Installer,9420,000,1SAP2.P.9420.000.5066612,-4.00,0.00,-4.00,1SAP2,OY.
546871,"Sabur, Ali",2019-10-31,FS Installer,9420,000,1SAP2.P.9420.000.5066612,-10.00,0.00,-10.00,1SAP2,OY.
546872,"Sabur, Ali",2019-10-17,FS Installer,9420,000,1SAP2.P.9420.000.5328120,10.00,0.00,10.00,1SAP2,OY.
546873,"Sabur, Ali",2019-10-30,FS Installer,9420,000,1SAP2.P.9420.000.5066612,-10.00,0.00,-10.00,1SAP2,OY.
546874,"Johnson, Emile",2020-06-24,SIT,8440,238,1SAP2.C.8440.238.4247059,1.00,0.00,1.00,1SAP2,OY.
551247,"Bencivenga, Thomas",2019-08-19,Voice O&M Support,9500,619,1SAP2.C.9500.619.4464845,0.00,0.00,0.00,1SAP2,OY.
563327,"Crewe, Thomas",2019-09-17,CD&D/BOM Survey,9440,218,1SAP2.C.9440.218.5375908,0.00,0.00,0.00,1SAP2,OY.
564555,"Key, Larry",2019-08-06,Switch Tech,9440,228,1SAP2.C.9440.228.3722235,0.00,0.00,0.00,1SAP2,OY.
564831,"Key, Larry",2019-08-03,Switch Tech,9440,228,1SAP2.C.9440.228.3722235,0.00,0.00,0.00,1SAP2,OY.
564923,"Key, Larry",2019-08-05,Switch Tech,9440,228,1SAP2.C.9440.228.3722235,0.00,0.00,0.00,1SAP2,OY.
593592,"Tucker, Richard",2019-10-28,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00,1SAP2,OY.
593593,"Tucker, Richard",2019-12-02,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00,1SAP2,OY.
593685,"Tucker, Richard",2019-12-02,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00,1SAP2,OY.
593847,"Tucker, Richard",2019-12-03,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00,1SAP2,OY.
593935,"Tucker, Richard",2019-10-29,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00,1SAP2,OY.
593936,"Tucker, Richard",2019-10-30,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00,1SAP2,OY.
594023,"Tucker, Richard",2019-08-13,AMX Programmer,9440,328,1SAP2.C.9440.328.4697933,0.00,0.00,0.00,1SAP2,OY.
594102,"Tucker, Richard",2019-08-12,AMX Programmer (Local),9440,325,1SAP2.C.9440.325,0.00,0.00,0.00,1SAP2,OY.

In [345]:
# check data
df[df['WBS'].isnull()]

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr
60440,"WASSON, VANCE D",2017-04-17,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7
187713,"MCHUGH, ANTHONY T",2017-07-19,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7
188218,"MCHUGH, ANTHONY T",2017-05-11,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7
392182,"TROVINGER, TONY L",2017-03-30,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,1.00,0.00,1.00,1SAP2,OY7
392208,"TROVINGER, TONY L",2017-05-30,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7
392235,"TROVINGER, TONY L",2017-08-01,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7
392237,"TROVINGER, TONY L",2017-08-02,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,2.00,0.00,2.00,1SAP2,OY7
392482,"TROVINGER, TONY L",2017-07-20,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,2.00,0.00,2.00,1SAP2,OY7
392701,"TROVINGER, TONY L",2017-03-29,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,2.00,0.00,2.00,1SAP2,OY7
392728,"TROVINGER, TONY L",2017-05-23,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,1.00,0.00,1.00,1SAP2,OY7
392758,"TROVINGER, TONY L",2017-08-01,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,1.00,0.00,1.00,1SAP2,OY7
392760,"TROVINGER, TONY L",2017-08-02,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7
393018,"TROVINGER, TONY L",2017-07-19,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,1.00,0.00,1.00,1SAP2,OY7
559473,"Beylor, Larry",2017-05-15,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7
559715,"Beylor, Larry",2017-05-16,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7
560518,"Beylor, Larry",2017-04-03,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7
560524,"Beylor, Larry",2017-04-19,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7
560784,"Beylor, Larry",2017-08-02,CHG Code Not Available,7420,NaN,1SAP2.P.7420.000.NOCHGXX,0.00,0.00,0.00,1SAP2,OY7

In [346]:
df.head(3)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,1SAP2,OY7
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7

In [347]:
# add tpid character count column
df['tpid_length'] = df['TPID'].str.len()
df.head(3)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,1SAP2,OY7,24
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7,16
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7,16

In [348]:
# check metadata
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595850 entries, 0 to 595849
Data columns (total 12 columns):
User           595850 non-null object
Work Date      595850 non-null datetime64[ns]
Description    595850 non-null object
CLIN           595850 non-null object
WBS            595832 non-null object
TPID           595850 non-null object
Straight       595850 non-null float64
Overtime       595850 non-null float64
Total          595850 non-null float64
ID             595850 non-null object
OptYr          595850 non-null object
tpid_length    595850 non-null int64
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 54.6+ MB

In [349]:
# count number of rows associated with different values of id
df['ID'].value_counts()

1SAP2    595018
1SFSP       646
1SFN5        63
1SCB3        46
1SCA2        26
1SCN5        22
1SFA2         9
1SFB3         6
1SFB4         5
1SXN5         5
1S10P         3
1SF01         1
Name: ID, dtype: int64

In [350]:
df[df['ID'] == '1SF01']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
258735,"LOWE, SHAWN",2017-05-01,ALLHAND,0711,451,1SF01.T.0711.451.ALLHAND,0.00,0.00,0.00,1SF01,OY7,24

In [371]:
df[(df['ID'] == '1SF01') & (df['tpid_length'] != 24)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [351]:
df[df['ID'] == '1S10P']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
544186,"Wali, Sam",2019-02-27,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,1S10P,OY9,17
544187,"Wali, Sam",2019-03-01,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,1S10P,OY9,17
544188,"Wali, Sam",2019-02-28,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,1S10P,OY9,17

In [372]:
df[(df['ID'] == '1S10P') & (df['tpid_length'] != 17)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [373]:
df[df['ID'] == '1SXN5']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
472601,"Toler, Joseph",2019-02-04,Unbillable PMO,UNBL,000,1SXN5.P.UNBL.000.PMOUNBL,0.00,0.00,0.00,1SXN5,OY9,24
472603,"Toler, Joseph",2019-02-07,Unbillable PMO,UNBL,000,1SXN5.P.UNBL.000.PMOUNBL,0.00,0.00,0.00,1SXN5,OY9,24
473355,"Toler, Joseph",2019-02-05,Unbillable PMO,UNBL,000,1SXN5.P.UNBL.000.PMOUNBL,0.00,0.00,0.00,1SXN5,OY9,24
473356,"Toler, Joseph",2019-02-08,Unbillable PMO,UNBL,000,1SXN5.P.UNBL.000.PMOUNBL,0.00,0.00,0.00,1SXN5,OY9,24
473551,"Toler, Joseph",2019-02-06,Unbillable PMO,UNBL,000,1SXN5.P.UNBL.000.PMOUNBL,0.00,0.00,0.00,1SXN5,OY9,24

In [374]:
df[(df['ID'] == '1SXN5') & (df['tpid_length'] != 24)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [375]:
df[df['ID'] == '1SFB4']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
440517,"HAYES, LARON",2018-01-22,Express Direct Service,4520,425,1SFB4.T.4520.425.0345616,0.00,0.00,0.00,1SFB4,OY8,24
440550,"HAYES, LARON",2018-01-24,Express Direct Service,4520,425,1SFB4.T.4520.425.0345616,0.00,0.00,0.00,1SFB4,OY8,24
440609,"HAYES, LARON",2018-01-23,Express Direct Service,4520,425,1SFB4.T.4520.425.0345616,0.00,0.00,0.00,1SFB4,OY8,24
440610,"HAYES, LARON",2018-01-26,Express Direct Service,4520,425,1SFB4.T.4520.425.0345616,0.00,0.00,0.00,1SFB4,OY8,24
440694,"HAYES, LARON",2018-01-25,Express Direct Service,4520,425,1SFB4.T.4520.425.0345616,0.00,0.00,0.00,1SFB4,OY8,24

In [376]:
df[(df['ID'] == '1SFB4') & (df['tpid_length'] != 24)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [377]:
df[df['ID'] == '1SFB3']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
281228,"SEAGLE, THOMAS M",2017-09-08,ENOC SWING SHIFT,3330,000,1SFB3.G.3330.000.ENOCSWI,0.00,8.00,8.00,1SFB3,OY8,24
281268,"SEAGLE, THOMAS M",2017-09-02,ENOC SWING SHIFT,3330,000,1SFB3.G.3330.000.ENOCSWI,0.00,6.50,6.50,1SFB3,OY8,24
281269,"SEAGLE, THOMAS M",2017-09-06,ENOC SWING SHIFT,3330,000,1SFB3.G.3330.000.ENOCSWI,0.00,8.00,8.00,1SFB3,OY8,24
281283,"SEAGLE, THOMAS M",2017-09-07,ENOC SWING SHIFT,3330,000,1SFB3.G.3330.000.ENOCSWI,0.00,8.00,8.00,1SFB3,OY8,24
281310,"SEAGLE, THOMAS M",2017-09-03,ENOC SWING SHIFT,3330,000,1SFB3.G.3330.000.ENOCSWI,0.00,0.00,0.00,1SFB3,OY8,24
281311,"SEAGLE, THOMAS M",2017-09-04,ENOC SWING SHIFT,3330,000,1SFB3.G.3330.000.ENOCSWI,0.00,0.00,0.00,1SFB3,OY8,24

In [379]:
df[(df['ID'] == '1SFB3') & (df['tpid_length'] != 24)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [380]:
df[df['ID'] == '1SFA2']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
318386,"ALLEN, ZACKARY F",2017-11-08,Training,2420,000,1SFA2.D.2420.000.TRAINXX,0.00,0.00,0.00,1SFA2,OY8,24
356656,"CURTIS, ALEXANDRA L",2018-04-24,Training,2420,000,1SFA2.D.2420.000.TRAINXX,4.00,0.00,4.00,1SFA2,OY8,24
377210,"WRIGHT, CHRISTOPHER J",2017-04-21,WEST INSTALLER,2410,423,1SFA2.D.2410.423.WESTINS,0.00,0.00,0.00,1SFA2,OY7,24
562906,"Crewe, Thomas",2017-04-04,CHG Code not available,2420,000,1SFA2.D.2420.000.NOCHGXX,0.00,0.00,0.00,1SFA2,OY7,24
562909,"Crewe, Thomas",2017-05-08,CHG Code not available,2420,000,1SFA2.D.2420.000.NOCHGXX,0.00,0.00,0.00,1SFA2,OY7,24
563009,"Crewe, Thomas",2017-05-01,CHG Code not available,2420,000,1SFA2.D.2420.000.NOCHGXX,0.00,0.00,0.00,1SFA2,OY7,24
563260,"Crewe, Thomas",2017-12-11,CHG Code not available,2420,000,1SFA2.D.2420.000.NOCHGXX,0.00,0.00,0.00,1SFA2,OY8,24
563331,"Crewe, Thomas",2017-04-05,CHG Code not available,2420,000,1SFA2.D.2420.000.NOCHGXX,0.00,0.00,0.00,1SFA2,OY7,24
563333,"Crewe, Thomas",2017-04-25,CHG Code not available,2420,000,1SFA2.D.2420.000.NOCHGXX,0.00,0.00,0.00,1SFA2,OY7,24

In [381]:
df[(df['ID'] == '1SFA2') & (df['tpid_length'] != 24)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [382]:
df[df['ID'] == '1SCN5']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
195603,"LEWIS, DAVID R",2017-03-31,Proj Mgmt Supt (D Org),5401,401,1SCN5.D.5401.401.0419653,4.00,0.00,4.00,1SCN5,OY7,24
195804,"LEWIS, DAVID R",2017-03-30,Proj Mgmt Supt (D Org),5401,401,1SCN5.D.5401.401.0419653,8.00,0.00,8.00,1SCN5,OY7,24
196017,"LEWIS, DAVID R",2017-03-29,Proj Mgmt Supt (D Org),5401,401,1SCN5.D.5401.401.0419653,8.00,0.00,8.00,1SCN5,OY7,24
300683,"HALL, KIP R",2017-04-05,Guam,5342,922,1SCN5.M.5342.922.0000000,-2.00,0.00,-2.00,1SCN5,OY7,24
300936,"HALL, KIP R",2017-04-06,Guam,5342,922,1SCN5.M.5342.922.0000000,-3.00,0.00,-3.00,1SCN5,OY7,24
300983,"HALL, KIP R",2017-04-05,Guam,5342,922,1SCN5.M.5342.922.0000000,2.00,0.00,2.00,1SCN5,OY7,24
300984,"HALL, KIP R",2017-04-06,Guam,5342,922,1SCN5.M.5342.922.0000000,3.00,0.00,3.00,1SCN5,OY7,24
382096,"MITCHELL, VAN E",2017-03-21,Telephone Support,5970,840,1SCN5.S.5970.840.0000000,0.00,0.00,0.00,1SCN5,OY7,24
382162,"MITCHELL, VAN E",2017-03-20,Telephone Support,5970,840,1SCN5.S.5970.840.0000000,0.00,0.00,0.00,1SCN5,OY7,24
382164,"MITCHELL, VAN E",2017-03-22,Telephone Support,5970,840,1SCN5.S.5970.840.0000000,0.00,0.00,0.00,1SCN5,OY7,24
382233,"MITCHELL, VAN E",2017-03-23,Telephone Support,5970,840,1SCN5.S.5970.840.0000000,0.00,0.00,0.00,1SCN5,OY7,24
382309,"MITCHELL, VAN E",2017-03-24,Telephone Support,5970,840,1SCN5.S.5970.840.0000000,0.00,0.00,0.00,1SCN5,OY7,24
573824,"Herrin, David",2017-03-29,Product Integ Team (PIT),5401,404,1SCN5.D.5401.404.0000000,0.00,0.00,0.00,1SCN5,OY7,24
573921,"Herrin, David",2017-03-21,Product Integ Team (PIT),5401,404,1SCN5.D.5401.404.0000000,0.00,0.00,0.00,1SCN5,OY7,24
573922,"Herrin, David",2017-03-24,Product Integ Team (PIT),5401,404,1SCN5.D.5401.404.0000000,0.00,0.00,0.00,1SCN5,OY7,24
573923,"Herrin, David",2017-03-28,Product Integ Team (PIT),5401,404,1SCN5.D.5401.404.0000000,0.00,0.00,0.00,1SCN5,OY7,24
573924,"Herrin, David",2017-03-30,Product Integ Team (PIT),5401,404,1SCN5.D.5401.404.0000000,0.00,0.00,0.00,1SCN5,OY7,24
573995,"Herrin, David",2017-03-22,Product Integ Team (PIT),5401,404,1SCN5.D.5401.404.0000000,0.00,0.00,0.00,1SCN5,OY7,24
574027,"Herrin, David",2017-03-20,Product Integ Team (PIT),5401,404,1SCN5.D.5401.404.0000000,0.00,0.00,0.00,1SCN5,OY7,24
574028,"Herrin, David",2017-03-23,Product Integ Team (PIT),5401,404,1SCN5.D.5401.404.0000000,0.00,0.00,0.00,1SCN5,OY7,24
574029,"Herrin, David",2017-03-27,Product Integ Team (PIT),5401,404,1SCN5.D.5401.404.0000000,0.00,0.00,0.00,1SCN5,OY7,24
574031,"Herrin, David",2017-03-31,Product Integ Team (PIT),5401,404,1SCN5.D.5401.404.0000000,0.00,0.00,0.00,1SCN5,OY7,24

In [383]:
df[(df['ID'] == '1SCN5') & (df['tpid_length'] != 24)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [384]:
df[df['ID'] == '1SCA2']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
44465,"CROCKETT, LESTER M",2017-05-23,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24
44467,"CROCKETT, LESTER M",2017-05-30,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
44471,"CROCKETT, LESTER M",2017-06-13,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
44568,"CROCKETT, LESTER M",2017-03-28,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24
44569,"CROCKETT, LESTER M",2017-04-11,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
44570,"CROCKETT, LESTER M",2017-04-18,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24
44573,"CROCKETT, LESTER M",2017-05-09,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
44582,"CROCKETT, LESTER M",2017-06-27,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,0.00,0.00,0.00,1SCA2,OY7,24
44675,"CROCKETT, LESTER M",2017-05-30,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24
44771,"CROCKETT, LESTER M",2017-04-25,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24
44772,"CROCKETT, LESTER M",2017-04-25,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
44785,"CROCKETT, LESTER M",2017-06-20,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.50,0.00,-1.50,1SCA2,OY7,24
44874,"CROCKETT, LESTER M",2017-03-28,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
44881,"CROCKETT, LESTER M",2017-05-02,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
44889,"CROCKETT, LESTER M",2017-06-06,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24
44890,"CROCKETT, LESTER M",2017-06-06,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
44893,"CROCKETT, LESTER M",2017-06-27,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,0.00,0.00,0.00,1SCA2,OY7,24
44990,"CROCKETT, LESTER M",2017-05-16,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24
44998,"CROCKETT, LESTER M",2017-06-20,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.50,0.00,1.50,1SCA2,OY7,24
45092,"CROCKETT, LESTER M",2017-04-18,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
45095,"CROCKETT, LESTER M",2017-05-16,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
45188,"CROCKETT, LESTER M",2017-04-11,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24
45194,"CROCKETT, LESTER M",2017-05-02,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24
45195,"CROCKETT, LESTER M",2017-05-09,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24
45198,"CROCKETT, LESTER M",2017-05-23,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,-1.00,0.00,-1.00,1SCA2,OY7,24
45201,"CROCKETT, LESTER M",2017-06-13,PEEREVW,2401,601,1SCA2.D.2401.601.PEEREVW,1.00,0.00,1.00,1SCA2,OY7,24

In [385]:
df[(df['ID'] == '1SCA2') & (df['tpid_length'] != 24)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [386]:
df[df['ID'] == '1SCB3']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
24423,"PIERCE, HARVEY",2017-07-28,Logistics & Procurement,3400,411,1SCB3.D.3400.411.0000000,8.00,0.00,8.00,1SCB3,OY7,24
24503,"PIERCE, HARVEY",2017-07-25,Logistics & Procurement,3400,411,1SCB3.D.3400.411.0000000,-8.00,0.00,-8.00,1SCB3,OY7,24
24506,"PIERCE, HARVEY",2017-07-28,Logistics & Procurement,3400,411,1SCB3.D.3400.411.0000000,-8.00,0.00,-8.00,1SCB3,OY7,24
24573,"PIERCE, HARVEY",2017-07-25,Logistics & Procurement,3400,411,1SCB3.D.3400.411.0000000,8.00,0.00,8.00,1SCB3,OY7,24
24731,"PIERCE, HARVEY",2017-07-24,Logistics & Procurement,3400,411,1SCB3.D.3400.411.0000000,8.00,0.00,8.00,1SCB3,OY7,24
24734,"PIERCE, HARVEY",2017-07-26,Logistics & Procurement,3400,411,1SCB3.D.3400.411.0000000,8.00,0.00,8.00,1SCB3,OY7,24
24735,"PIERCE, HARVEY",2017-07-26,Logistics & Procurement,3400,411,1SCB3.D.3400.411.0000000,-8.00,0.00,-8.00,1SCB3,OY7,24
24812,"PIERCE, HARVEY",2017-07-27,Logistics & Procurement,3400,411,1SCB3.D.3400.411.0000000,8.00,0.00,8.00,1SCB3,OY7,24
24872,"PIERCE, HARVEY",2017-07-24,Logistics & Procurement,3400,411,1SCB3.D.3400.411.0000000,-8.00,0.00,-8.00,1SCB3,OY7,24
24950,"PIERCE, HARVEY",2017-07-27,Logistics & Procurement,3400,411,1SCB3.D.3400.411.0000000,-8.00,0.00,-8.00,1SCB3,OY7,24
82338,"NGUYEN, TAM M",2017-03-20,G/CE,3300,631,1SCB3.G.3300.631.0000000,0.00,0.00,0.00,1SCB3,OY7,24
361633,"JOHNSON, KEVIN",2017-03-21,I Mission Support,3300,682,1SCB3.G.3300.682.0000000,0.00,0.00,0.00,1SCB3,OY7,24
361635,"JOHNSON, KEVIN",2017-03-22,I Mission Support,3300,682,1SCB3.G.3300.682.0000000,9.50,0.00,9.50,1SCB3,OY7,24
361714,"JOHNSON, KEVIN",2017-03-21,I Mission Support,3300,682,1SCB3.G.3300.682.0000000,0.00,0.00,0.00,1SCB3,OY7,24
361765,"JOHNSON, KEVIN",2017-03-20,I Mission Support,3300,682,1SCB3.G.3300.682.0000000,12.00,0.00,12.00,1SCB3,OY7,24
361902,"JOHNSON, KEVIN",2017-03-20,I Mission Support,3300,682,1SCB3.G.3300.682.0000000,-12.00,0.00,-12.00,1SCB3,OY7,24
362014,"JOHNSON, KEVIN",2017-03-22,I Mission Support,3300,682,1SCB3.G.3300.682.0000000,-9.50,0.00,-9.50,1SCB3,OY7,24
486572,"Whitfield, Erika",2017-03-28,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
486573,"Whitfield, Erika",2017-03-30,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
486638,"Whitfield, Erika",2019-12-03,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,8.00,0.00,8.00,1SCB3,OY.,24
486639,"Whitfield, Erika",2019-12-04,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,-8.00,0.00,-8.00,1SCB3,OY.,24
486640,"Whitfield, Erika",2019-12-06,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,8.00,0.00,8.00,1SCB3,OY.,24
486708,"Whitfield, Erika",2019-11-26,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,12.00,0.00,12.00,1SCB3,OY.,24
486709,"Whitfield, Erika",2017-03-27,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
486710,"Whitfield, Erika",2017-03-29,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
486787,"Whitfield, Erika",2019-11-25,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,-12.00,0.00,-12.00,1SCB3,OY.,24
486788,"Whitfield, Erika",2019-12-02,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,-6.00,0.00,-6.00,1SCB3,OY.,24
486789,"Whitfield, Erika",2017-03-20,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
486790,"Whitfield, Erika",2017-03-23,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
486793,"Whitfield, Erika",2017-03-31,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
486847,"Whitfield, Erika",2019-11-25,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,12.00,0.00,12.00,1SCB3,OY.,24
486848,"Whitfield, Erika",2019-12-02,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,6.00,0.00,6.00,1SCB3,OY.,24
486851,"Whitfield, Erika",2017-03-24,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
486854,"Whitfield, Erika",2017-04-03,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
486990,"Whitfield, Erika",2019-11-26,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,-12.00,0.00,-12.00,1SCB3,OY.,24
486991,"Whitfield, Erika",2019-11-29,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,8.00,0.00,8.00,1SCB3,OY.,24
486992,"Whitfield, Erika",2019-11-29,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,-8.00,0.00,-8.00,1SCB3,OY.,24
486993,"Whitfield, Erika",2019-12-03,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,-8.00,0.00,-8.00,1SCB3,OY.,24
486994,"Whitfield, Erika",2019-12-06,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,-8.00,0.00,-8.00,1SCB3,OY.,24
486995,"Whitfield, Erika",2017-03-21,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
487058,"Whitfield, Erika",2019-11-27,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,-6.00,0.00,-6.00,1SCB3,OY.,24
487059,"Whitfield, Erika",2019-12-04,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,8.00,0.00,8.00,1SCB3,OY.,24
487060,"Whitfield, Erika",2019-12-05,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,8.00,0.00,8.00,1SCB3,OY.,24
487061,"Whitfield, Erika",2019-12-05,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,-8.00,0.00,-8.00,1SCB3,OY.,24
487063,"Whitfield, Erika",2017-03-22,Regional Commun (AST),3340,801,1SCB3.G.3340.801.0000000,0.00,0.00,0.00,1SCB3,OY7,24
487128,"Whitfield, Erika",2019-11-27,Regional Communications,3340,000,1SCB3.G.3340.000.0000000,6.00,0.00,6.00,1SCB3,OY.,24

In [387]:
df[(df['ID'] == '1SCB3') & (df['tpid_length'] != 24)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [388]:
df[df['ID'] == '1SFN5']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
127768,"GLEASON, JAMES F",2017-03-21,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,12.00,0.00,12.00,1SFN5,OY7,24
127769,"GLEASON, JAMES F",2017-03-23,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,12.00,0.00,12.00,1SFN5,OY7,24
127770,"GLEASON, JAMES F",2017-03-24,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,8.00,0.00,8.00,1SFN5,OY7,24
127774,"GLEASON, JAMES F",2017-04-06,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-12.00,0.00,-12.00,1SFN5,OY7,24
127775,"GLEASON, JAMES F",2017-04-10,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,0.00,0.00,0.00,1SFN5,OY7,24
127858,"GLEASON, JAMES F",2017-03-20,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,0.00,0.00,0.00,1SFN5,OY7,24
127859,"GLEASON, JAMES F",2017-03-22,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,8.00,0.00,8.00,1SFN5,OY7,24
127861,"GLEASON, JAMES F",2017-03-27,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-7.50,0.00,-7.50,1SFN5,OY7,24
127862,"GLEASON, JAMES F",2017-03-30,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,8.50,0.00,8.50,1SFN5,OY7,24
127863,"GLEASON, JAMES F",2017-03-30,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-8.50,0.00,-8.50,1SFN5,OY7,24
127864,"GLEASON, JAMES F",2017-04-03,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-8.00,0.00,-8.00,1SFN5,OY7,24
127866,"GLEASON, JAMES F",2017-04-14,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,0.00,0.00,0.00,1SFN5,OY7,24
127925,"GLEASON, JAMES F",2017-03-20,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,0.00,0.00,0.00,1SFN5,OY7,24
127926,"GLEASON, JAMES F",2017-03-23,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-12.00,0.00,-12.00,1SFN5,OY7,24
127928,"GLEASON, JAMES F",2017-03-28,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-8.00,0.00,-8.00,1SFN5,OY7,24
127929,"GLEASON, JAMES F",2017-03-31,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-8.00,0.00,-8.00,1SFN5,OY7,24
127930,"GLEASON, JAMES F",2017-04-03,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,8.00,0.00,8.00,1SFN5,OY7,24
127931,"GLEASON, JAMES F",2017-04-04,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,8.00,0.00,8.00,1SFN5,OY7,24
127932,"GLEASON, JAMES F",2017-04-07,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,8.00,0.00,8.00,1SFN5,OY7,24
128004,"GLEASON, JAMES F",2017-04-05,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,0.00,0.00,0.00,1SFN5,OY7,24
128007,"GLEASON, JAMES F",2017-04-12,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,0.00,0.00,0.00,1SFN5,OY7,24
128079,"GLEASON, JAMES F",2017-03-22,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-8.00,0.00,-8.00,1SFN5,OY7,24
128083,"GLEASON, JAMES F",2017-04-07,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-8.00,0.00,-8.00,1SFN5,OY7,24
128150,"GLEASON, JAMES F",2017-03-28,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,8.00,0.00,8.00,1SFN5,OY7,24
128151,"GLEASON, JAMES F",2017-03-29,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-8.00,0.00,-8.00,1SFN5,OY7,24
128153,"GLEASON, JAMES F",2017-04-13,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,0.00,0.00,0.00,1SFN5,OY7,24
128228,"GLEASON, JAMES F",2017-03-29,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,8.00,0.00,8.00,1SFN5,OY7,24
128229,"GLEASON, JAMES F",2017-04-04,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-8.00,0.00,-8.00,1SFN5,OY7,24
128299,"GLEASON, JAMES F",2017-03-21,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-12.00,0.00,-12.00,1SFN5,OY7,24
128300,"GLEASON, JAMES F",2017-03-24,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,-8.00,0.00,-8.00,1SFN5,OY7,24
...,...,...,...,...,...,...,...,...,...,...,...,...
128304,"GLEASON, JAMES F",2017-04-06,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,12.00,0.00,12.00,1SFN5,OY7,24
128305,"GLEASON, JAMES F",2017-04-11,Internal Tickets,5410,422,1SFN5.D.5410.422.INTERNL,0.00,0.00,0.00,1SFN5,OY7,24
179215,"TRABAL, WILSON",2017-06-19,VIDEO RACK FAB CLEANUP,5410,423,1SFN5.D.5410.423.VIDRCLN,2.00,0.00,2.00,1SFN5,OY7,24
179298,"TRABAL, WILSON",2017-03-31,VIDEO RACK FAB CLEANUP,5410,423,1SFN5.D.5410.423.VIDRCLN,2.00,0.00,2.00,1SFN5,OY7,24
301777,"PERKINS-TOURE, DAWN C",2017-03-21,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,7.50,0.00,7.50,1SFN5,OY7,24
301778,"PERKINS-TOURE, DAWN C",2017-03-28,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,7.50,0.00,7.50,1SFN5,OY7,24
301855,"PERKINS-TOURE, DAWN C",2017-03-30,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,11.00,0.00,11.00,1SFN5,OY7,24
301937,"PERKINS-TOURE, DAWN C",2017-03-24,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,9.00,0.00,9.00,1SFN5,OY7,24
302011,"PERKINS-TOURE, DAWN C",2017-03-22,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,-8.00,0.00,-8.00,1SFN5,OY7,24
302093,"PERKINS-TOURE, DAWN C",2017-03-29,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,7.50,0.00,7.50,1SFN5,OY7,24
302094,"PERKINS-TOURE, DAWN C",2017-03-31,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,6.50,0.00,6.50,1SFN5,OY7,24
302095,"PERKINS-TOURE, DAWN C",2017-04-03,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,0.00,0.00,0.00,1SFN5,OY7,24
302159,"PERKINS-TOURE, DAWN C",2017-03-20,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,-7.50,0.00,-7.50,1SFN5,OY7,24
302161,"PERKINS-TOURE, DAWN C",2017-03-23,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,-8.00,0.00,-8.00,1SFN5,OY7,24
302251,"PERKINS-TOURE, DAWN C",2017-03-20,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,7.50,0.00,7.50,1SFN5,OY7,24
302252,"PERKINS-TOURE, DAWN C",2017-03-21,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,-7.50,0.00,-7.50,1SFN5,OY7,24
302254,"PERKINS-TOURE, DAWN C",2017-03-22,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,8.00,0.00,8.00,1SFN5,OY7,24
302255,"PERKINS-TOURE, DAWN C",2017-03-24,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,-9.00,0.00,-9.00,1SFN5,OY7,24
302256,"PERKINS-TOURE, DAWN C",2017-03-27,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,8.00,0.00,8.00,1SFN5,OY7,24
302334,"PERKINS-TOURE, DAWN C",2017-03-23,WESTDSP,5410,423,1SFN5.D.5410.423.WESTDSP,8.00,0.00,8.00,1SFN5,OY7,24
558129,"Ferguson, Jerry",2017-03-22,SATCOM TEAM,5330,000,1SFN5.M.5330.000.SATCOMT,0.00,0.00,0.00,1SFN5,OY7,24
558130,"Ferguson, Jerry",2017-04-05,SATCOM TEAM,5330,000,1SFN5.M.5330.000.SATCOMT,0.00,0.00,0.00,1SFN5,OY7,24
558142,"Ferguson, Jerry",2017-03-28,SATCOM TEAM,5330,000,1SFN5.M.5330.000.SATCOMT,0.00,0.00,0.00,1SFN5,OY7,24
558159,"Ferguson, Jerry",2017-03-21,SATCOM TEAM,5330,000,1SFN5.M.5330.000.SATCOMT,0.00,0.00,0.00,1SFN5,OY7,24
558161,"Ferguson, Jerry",2017-03-24,SATCOM TEAM,5330,000,1SFN5.M.5330.000.SATCOMT,0.00,0.00,0.00,1SFN5,OY7,24
558162,"Ferguson, Jerry",2017-04-03,SATCOM TEAM,5330,000,1SFN5.M.5330.000.SATCOMT,0.00,0.00,0.00,1SFN5,OY7,24
558163,"Ferguson, Jerry",2017-04-06,SATCOM TEAM,5330,000,1SFN5.M.5330.000.SATCOMT,0.00,0.00,0.00,1SFN5,OY7,24
558170,"Ferguson, Jerry",2017-03-27,SATCOM TEAM,5330,000,1SFN5.M.5330.000.SATCOMT,0.00,0.00,0.00,1SFN5,OY7,24
558171,"Ferguson, Jerry",2017-03-30,SATCOM TEAM,5330,000,1SFN5.M.5330.000.SATCOMT,0.00,0.00,0.00,1SFN5,OY7,24
558181,"Ferguson, Jerry",2017-04-04,SATCOM TEAM,5330,000,1SFN5.M.5330.000.SATCOMT,0.00,0.00,0.00,1SFN5,OY7,24

In [389]:
df[(df['ID'] == '1SFN5') & (df['tpid_length'] != 24)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [390]:
df[df['ID'] == '1SFSP']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
11277,"TIMMONS, CARL A",2017-03-20,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421289,3.00,0.00,3.00,1SFSP,OY7,24
11480,"TIMMONS, CARL A",2017-04-04,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421289,2.00,0.00,2.00,1SFSP,OY7,24
28323,"JONES, KATHLINE E",2017-06-13,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,0.00,5.00,5.00,1SFSP,OY7,24
31755,"SHINGLES, VELGAMON C",2017-03-30,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0419653,8.00,0.00,8.00,1SFSP,OY7,24
60539,"WASSON, VANCE D",2017-03-24,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0376518,1.00,0.00,1.00,1SFSP,OY7,24
60661,"WASSON, VANCE D",2017-03-22,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0376518,1.00,0.00,1.00,1SFSP,OY7,24
60790,"WASSON, VANCE D",2017-03-20,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0376518,5.00,0.00,5.00,1SFSP,OY7,24
61299,"WASSON, VANCE D",2017-03-21,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0376518,2.50,0.00,2.50,1SFSP,OY7,24
106380,"DEHN, ALBERT W",2017-03-20,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421289,4.00,0.00,4.00,1SFSP,OY7,24
106383,"DEHN, ALBERT W",2017-04-05,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,0.00,5.00,5.00,1SFSP,OY7,24
106403,"DEHN, ALBERT W",2017-09-20,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,-8.00,0.00,-8.00,1SFSP,OY8,24
106404,"DEHN, ALBERT W",2017-09-25,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,3.00,0.00,3.00,1SFSP,OY8,24
106405,"DEHN, ALBERT W",2017-09-27,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY8,24
106406,"DEHN, ALBERT W",2017-10-04,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY8,24
106407,"DEHN, ALBERT W",2017-10-04,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,-8.00,0.00,-8.00,1SFSP,OY8,24
106409,"DEHN, ALBERT W",2017-10-12,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY8,24
106411,"DEHN, ALBERT W",2017-10-17,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,-8.00,0.00,-8.00,1SFSP,OY8,24
106412,"DEHN, ALBERT W",2017-10-20,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY8,24
106413,"DEHN, ALBERT W",2017-10-20,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,-8.00,0.00,-8.00,1SFSP,OY8,24
106489,"DEHN, ALBERT W",2017-04-06,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY7,24
106490,"DEHN, ALBERT W",2017-04-07,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY7,24
106505,"DEHN, ALBERT W",2017-09-19,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY8,24
106507,"DEHN, ALBERT W",2017-09-27,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,-8.00,0.00,-8.00,1SFSP,OY8,24
106509,"DEHN, ALBERT W",2017-10-24,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,0.00,0.00,0.00,1SFSP,OY8,24
106513,"DEHN, ALBERT W",2017-11-20,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY8,24
106560,"DEHN, ALBERT W",2017-03-31,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421289,4.00,0.00,4.00,1SFSP,OY7,24
106577,"DEHN, ALBERT W",2017-09-26,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY8,24
106578,"DEHN, ALBERT W",2017-09-26,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,-8.00,0.00,-8.00,1SFSP,OY8,24
106579,"DEHN, ALBERT W",2017-10-11,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,-8.00,0.00,-8.00,1SFSP,OY8,24
106581,"DEHN, ALBERT W",2017-10-19,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY8,24
...,...,...,...,...,...,...,...,...,...,...,...,...
577330,"Sorenson, Troy",2017-03-31,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0386883,5.50,0.00,5.50,1SFSP,OY7,24
582129,"Johnson, Kristopher",2017-04-12,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421289,0.00,0.00,0.00,1SFSP,OY7,24
582187,"Johnson, Kristopher",2017-04-11,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421289,5.00,0.00,5.00,1SFSP,OY7,24
582200,"Smith, Timothy",2017-04-23,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0424237,8.00,0.00,8.00,1SFSP,OY7,24
593515,"Tucker, Richard",2017-03-21,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423970,5.00,0.00,5.00,1SFSP,OY7,24
593520,"Tucker, Richard",2017-04-03,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,4.00,0.00,4.00,1SFSP,OY7,24
593522,"Tucker, Richard",2017-04-24,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,12.50,0.00,12.50,1SFSP,OY7,24
593523,"Tucker, Richard",2017-04-26,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,1.00,0.00,1.00,1SFSP,OY7,24
593524,"Tucker, Richard",2017-05-02,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,13.00,0.00,13.00,1SFSP,OY7,24
593594,"Tucker, Richard",2017-04-05,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,11.00,0.00,11.00,1SFSP,OY7,24
593595,"Tucker, Richard",2017-04-06,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423970,2.00,0.00,2.00,1SFSP,OY7,24
593596,"Tucker, Richard",2017-05-01,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,5.00,0.00,5.00,1SFSP,OY7,24
593597,"Tucker, Richard",2017-05-03,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,6.00,0.00,6.00,1SFSP,OY7,24
593686,"Tucker, Richard",2017-03-20,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423970,12.00,0.00,12.00,1SFSP,OY7,24
593688,"Tucker, Richard",2017-03-27,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,3.00,0.00,3.00,1SFSP,OY7,24
593690,"Tucker, Richard",2017-04-19,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,2.00,0.00,2.00,1SFSP,OY7,24
593782,"Tucker, Richard",2017-04-20,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,3.00,0.00,3.00,1SFSP,OY7,24
593784,"Tucker, Richard",2017-04-25,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,12.50,0.00,12.50,1SFSP,OY7,24
593850,"Tucker, Richard",2017-04-17,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,4.00,0.00,4.00,1SFSP,OY7,24
593938,"Tucker, Richard",2017-03-22,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,10.00,0.00,10.00,1SFSP,OY7,24
593939,"Tucker, Richard",2017-03-22,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423970,1.00,0.00,1.00,1SFSP,OY7,24
593942,"Tucker, Richard",2017-05-03,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,2.00,0.00,2.00,1SFSP,OY7,24
594025,"Tucker, Richard",2017-04-06,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,2.00,0.00,2.00,1SFSP,OY7,24
594028,"Tucker, Richard",2017-05-09,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,2.00,0.00,2.00,1SFSP,OY7,24
594105,"Tucker, Richard",2017-04-04,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,3.50,0.00,3.50,1SFSP,OY7,24
594106,"Tucker, Richard",2017-04-18,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,3.00,0.00,3.00,1SFSP,OY7,24
594108,"Tucker, Richard",2017-05-04,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0421649,2.00,0.00,2.00,1SFSP,OY7,24
594350,"Helsley, Michael-Hank",2017-03-29,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY7,24
594446,"Helsley, Michael-Hank",2017-04-17,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY7,24
594539,"Helsley, Michael-Hank",2017-04-21,Project Instl Sup (D Org),5420,000,1SFSP.D.5420.000.0423799,8.00,0.00,8.00,1SFSP,OY7,24

In [391]:
df[(df['ID'] == '1SFSP') & (df['tpid_length'] != 24)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [394]:
df[df['ID'] == '1SAP2']

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,1SAP2,OY7,24
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7,16
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7,16
3,"THOMPSON, MORRIS R",2017-08-10,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
4,"THOMPSON, MORRIS R",2017-08-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
5,"THOMPSON, MORRIS R",2017-09-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
6,"THOMPSON, MORRIS R",2017-09-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
7,"THOMPSON, MORRIS R",2017-09-21,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
8,"THOMPSON, MORRIS R",2017-09-25,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
9,"THOMPSON, MORRIS R",2017-10-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
10,"THOMPSON, MORRIS R",2017-10-27,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
11,"THOMPSON, MORRIS R",2017-10-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
12,"THOMPSON, MORRIS R",2017-11-02,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
13,"THOMPSON, MORRIS R",2017-11-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
14,"THOMPSON, MORRIS R",2017-11-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
15,"THOMPSON, MORRIS R",2017-11-17,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
16,"THOMPSON, MORRIS R",2017-11-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
17,"THOMPSON, MORRIS R",2017-11-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
18,"THOMPSON, MORRIS R",2017-11-29,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
19,"THOMPSON, MORRIS R",2017-12-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
20,"THOMPSON, MORRIS R",2018-01-16,Asset Management,8400,514,1SAP2.C.8400.514,4.00,0.00,4.00,1SAP2,OY8,16
21,"THOMPSON, MORRIS R",2018-01-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
22,"THOMPSON, MORRIS R",2018-02-12,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
23,"THOMPSON, MORRIS R",2018-02-20,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00,1SAP2,OY8,16
24,"THOMPSON, MORRIS R",2018-02-23,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00,1SAP2,OY8,16
25,"THOMPSON, MORRIS R",2018-02-23,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8,16
26,"THOMPSON, MORRIS R",2018-03-05,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
27,"THOMPSON, MORRIS R",2018-03-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
28,"THOMPSON, MORRIS R",2018-03-07,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8,16
29,"THOMPSON, MORRIS R",2018-03-16,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8,16
...,...,...,...,...,...,...,...,...,...,...,...,...
595820,"Simmons, Kenneth",2017-05-02,D Mission Support,7300,683,1SAP2.C.7300.683,9.00,0.00,9.00,1SAP2,OY7,16
595821,"Simmons, Kenneth",2017-05-09,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595822,"Simmons, Kenneth",2017-05-18,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595823,"Simmons, Kenneth",2017-06-27,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7,16
595824,"Simmons, Kenneth",2017-06-28,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595825,"Simmons, Kenneth",2017-07-03,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50,1SAP2,OY7,16
595826,"Simmons, Kenneth",2017-07-05,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00,1SAP2,OY7,16
595827,"Simmons, Kenneth",2017-07-08,D Mission Support,7300,683,1SAP2.C.7300.683,4.50,0.00,4.50,1SAP2,OY7,16
595828,"Simmons, Kenneth",2017-03-29,D Mission Support,7300,683,1SAP2.C.7300.683,7.50,0.00,7.50,1SAP2,OY7,16
595829,"Simmons, Kenneth",2017-04-06,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00,1SAP2,OY7,16
595830,"Simmons, Kenneth",2017-04-19,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7,16
595831,"Simmons, Kenneth",2017-04-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595832,"Simmons, Kenneth",2017-04-26,D Mission Support,7300,683,1SAP2.C.7300.683,9.50,0.00,9.50,1SAP2,OY7,16
595833,"Simmons, Kenneth",2017-05-05,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595834,"Simmons, Kenneth",2017-05-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595835,"Simmons, Kenneth",2017-05-31,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7,16
595836,"Simmons, Kenneth",2017-06-06,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7,16
595837,"Simmons, Kenneth",2017-06-18,D Mission Support,7300,683,1SAP2.C.7300.683,13.00,0.00,13.00,1SAP2,OY7,16
595838,"Simmons, Kenneth",2017-06-21,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595839,"Simmons, Kenneth",2017-07-10,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595840,"Simmons, Kenneth",2017-07-13,D Mission Support,7300,683,1SAP2.C.7300.683,3.50,0.00,3.50,1SAP2,OY7,16
595841,"Simmons, Kenneth",2017-03-20,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595842,"Simmons, Kenneth",2017-03-23,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595843,"Simmons, Kenneth",2017-03-27,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00,1SAP2,OY7,16
595844,"Simmons, Kenneth",2017-04-17,D Mission Support,7300,683,1SAP2.C.7300.683,6.00,0.00,6.00,1SAP2,OY7,16
595845,"Simmons, Kenneth",2017-05-07,D Mission Support,7300,683,1SAP2.C.7300.683,14.00,0.00,14.00,1SAP2,OY7,16
595846,"Simmons, Kenneth",2017-05-10,D Mission Support,7300,683,1SAP2.C.7300.683,11.50,0.00,11.50,1SAP2,OY7,16
595847,"Simmons, Kenneth",2017-06-13,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7,16
595848,"Simmons, Kenneth",2017-07-06,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00,1SAP2,OY7,16
595849,"Simmons, Kenneth",2017-07-19,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50,1SAP2,OY7,16

In [395]:
df[(df['ID'] == '1SAP2') & (df['tpid_length'] == 16)]

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7,16
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,1SAP2,OY7,16
3,"THOMPSON, MORRIS R",2017-08-10,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
4,"THOMPSON, MORRIS R",2017-08-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
5,"THOMPSON, MORRIS R",2017-09-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
6,"THOMPSON, MORRIS R",2017-09-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
7,"THOMPSON, MORRIS R",2017-09-21,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
8,"THOMPSON, MORRIS R",2017-09-25,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
9,"THOMPSON, MORRIS R",2017-10-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
10,"THOMPSON, MORRIS R",2017-10-27,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
11,"THOMPSON, MORRIS R",2017-10-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
12,"THOMPSON, MORRIS R",2017-11-02,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
13,"THOMPSON, MORRIS R",2017-11-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
14,"THOMPSON, MORRIS R",2017-11-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
15,"THOMPSON, MORRIS R",2017-11-17,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
16,"THOMPSON, MORRIS R",2017-11-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
17,"THOMPSON, MORRIS R",2017-11-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
18,"THOMPSON, MORRIS R",2017-11-29,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
19,"THOMPSON, MORRIS R",2017-12-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
20,"THOMPSON, MORRIS R",2018-01-16,Asset Management,8400,514,1SAP2.C.8400.514,4.00,0.00,4.00,1SAP2,OY8,16
21,"THOMPSON, MORRIS R",2018-01-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
22,"THOMPSON, MORRIS R",2018-02-12,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
23,"THOMPSON, MORRIS R",2018-02-20,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00,1SAP2,OY8,16
24,"THOMPSON, MORRIS R",2018-02-23,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00,1SAP2,OY8,16
25,"THOMPSON, MORRIS R",2018-02-23,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8,16
26,"THOMPSON, MORRIS R",2018-03-05,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
27,"THOMPSON, MORRIS R",2018-03-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,1SAP2,OY8,16
28,"THOMPSON, MORRIS R",2018-03-07,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8,16
29,"THOMPSON, MORRIS R",2018-03-16,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,1SAP2,OY8,16
30,"THOMPSON, MORRIS R",2018-03-23,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,7.50,0.00,7.50,1SAP2,OY8,16
...,...,...,...,...,...,...,...,...,...,...,...,...
595820,"Simmons, Kenneth",2017-05-02,D Mission Support,7300,683,1SAP2.C.7300.683,9.00,0.00,9.00,1SAP2,OY7,16
595821,"Simmons, Kenneth",2017-05-09,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595822,"Simmons, Kenneth",2017-05-18,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595823,"Simmons, Kenneth",2017-06-27,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7,16
595824,"Simmons, Kenneth",2017-06-28,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595825,"Simmons, Kenneth",2017-07-03,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50,1SAP2,OY7,16
595826,"Simmons, Kenneth",2017-07-05,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00,1SAP2,OY7,16
595827,"Simmons, Kenneth",2017-07-08,D Mission Support,7300,683,1SAP2.C.7300.683,4.50,0.00,4.50,1SAP2,OY7,16
595828,"Simmons, Kenneth",2017-03-29,D Mission Support,7300,683,1SAP2.C.7300.683,7.50,0.00,7.50,1SAP2,OY7,16
595829,"Simmons, Kenneth",2017-04-06,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00,1SAP2,OY7,16
595830,"Simmons, Kenneth",2017-04-19,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7,16
595831,"Simmons, Kenneth",2017-04-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595832,"Simmons, Kenneth",2017-04-26,D Mission Support,7300,683,1SAP2.C.7300.683,9.50,0.00,9.50,1SAP2,OY7,16
595833,"Simmons, Kenneth",2017-05-05,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595834,"Simmons, Kenneth",2017-05-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595835,"Simmons, Kenneth",2017-05-31,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7,16
595836,"Simmons, Kenneth",2017-06-06,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7,16
595837,"Simmons, Kenneth",2017-06-18,D Mission Support,7300,683,1SAP2.C.7300.683,13.00,0.00,13.00,1SAP2,OY7,16
595838,"Simmons, Kenneth",2017-06-21,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595839,"Simmons, Kenneth",2017-07-10,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595840,"Simmons, Kenneth",2017-07-13,D Mission Support,7300,683,1SAP2.C.7300.683,3.50,0.00,3.50,1SAP2,OY7,16
595841,"Simmons, Kenneth",2017-03-20,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595842,"Simmons, Kenneth",2017-03-23,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,1SAP2,OY7,16
595843,"Simmons, Kenneth",2017-03-27,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00,1SAP2,OY7,16
595844,"Simmons, Kenneth",2017-04-17,D Mission Support,7300,683,1SAP2.C.7300.683,6.00,0.00,6.00,1SAP2,OY7,16
595845,"Simmons, Kenneth",2017-05-07,D Mission Support,7300,683,1SAP2.C.7300.683,14.00,0.00,14.00,1SAP2,OY7,16
595846,"Simmons, Kenneth",2017-05-10,D Mission Support,7300,683,1SAP2.C.7300.683,11.50,0.00,11.50,1SAP2,OY7,16
595847,"Simmons, Kenneth",2017-06-13,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,1SAP2,OY7,16
595848,"Simmons, Kenneth",2017-07-06,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00,1SAP2,OY7,16
595849,"Simmons, Kenneth",2017-07-19,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50,1SAP2,OY7,16

In [396]:
df[(df['ID'] == '1SAP2') & (df['tpid_length'] == 20)]

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total, ID, OptYr, tpid_length]
Index: []

In [397]:
df[(df['ID'] == '1SAP2') & (df['tpid_length'] == 24)]

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,1SAP2,OY7,24
56,"THOMPSON, MORRIS R",2017-07-11,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7,24
57,"THOMPSON, MORRIS R",2017-07-18,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7,24
127,"THOMPSON, MORRIS R",2017-07-17,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7,24
129,"THOMPSON, MORRIS R",2017-07-20,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,1SAP2,OY7,24
190,"THOMPSON, MORRIS R",2017-07-13,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7,24
256,"THOMPSON, MORRIS R",2017-07-12,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7,24
397,"THOMPSON, MORRIS R",2017-07-14,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,1SAP2,OY7,24
545,"BROWN, AUSTIN",2018-05-14,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,3.00,0.00,3.00,1SAP2,OY8,24
546,"BROWN, AUSTIN",2018-05-23,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,8.00,0.00,8.00,1SAP2,OY8,24
547,"BROWN, AUSTIN",2018-05-23,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,8.00,0.00,8.00,1SAP2,OY8,24
548,"BROWN, AUSTIN",2018-05-30,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,8.00,0.00,8.00,1SAP2,OY8,24
549,"BROWN, AUSTIN",2018-06-12,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,11.00,0.00,11.00,1SAP2,OY8,24
550,"BROWN, AUSTIN",2018-06-14,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,8.00,0.00,8.00,1SAP2,OY8,24
551,"BROWN, AUSTIN",2018-06-18,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,0.00,0.00,0.00,1SAP2,OY8,24
552,"BROWN, AUSTIN",2018-06-21,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,0.00,0.00,0.00,1SAP2,OY8,24
553,"BROWN, AUSTIN",2018-06-28,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,0.00,0.00,0.00,1SAP2,OY8,24
554,"BROWN, AUSTIN",2018-07-03,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,-8.00,0.00,-8.00,1SAP2,OY8,24
555,"BROWN, AUSTIN",2018-07-06,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,-6.00,0.00,-6.00,1SAP2,OY8,24
556,"BROWN, AUSTIN",2018-07-11,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,6.00,0.00,6.00,1SAP2,OY8,24
557,"BROWN, AUSTIN",2018-07-13,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,8.00,0.00,8.00,1SAP2,OY8,24
558,"BROWN, AUSTIN",2018-07-18,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,5.00,0.00,5.00,1SAP2,OY8,24
559,"BROWN, AUSTIN",2018-07-24,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,6.50,0.00,6.50,1SAP2,OY8,24
560,"BROWN, AUSTIN",2018-07-26,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,6.50,0.00,6.50,1SAP2,OY8,24
561,"BROWN, AUSTIN",2018-07-27,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,8.00,0.00,8.00,1SAP2,OY8,24
562,"BROWN, AUSTIN",2018-08-16,MGMADM,9330,000,1SAP2.F.9330.000.MGTMADM,9.00,0.00,9.00,1SAP2,OY9,24
563,"BROWN, AUSTIN",2018-08-28,MGMADM,9330,000,1SAP2.F.9330.000.MGTMADM,0.00,0.00,0.00,1SAP2,OY9,24
564,"BROWN, AUSTIN",2018-08-31,MGMADM,9330,000,1SAP2.F.9330.000.MGTMADM,0.00,0.00,0.00,1SAP2,OY9,24
565,"BROWN, AUSTIN",2018-10-05,MGMADM,9330,000,1SAP2.F.9330.000.MGTMADM,0.00,0.00,0.00,1SAP2,OY9,24
566,"BROWN, AUSTIN",2018-10-10,MGMADM,9330,000,1SAP2.F.9330.000.MGTMADM,0.00,0.00,0.00,1SAP2,OY9,24
...,...,...,...,...,...,...,...,...,...,...,...,...
595738,"Byers, Susan",2017-05-03,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.50,0.00,8.50,1SAP2,OY7,24
595739,"Byers, Susan",2017-05-04,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,1SAP2,OY7,24
595740,"Byers, Susan",2017-05-09,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,1SAP2,OY7,24
595741,"Byers, Susan",2017-05-10,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,1SAP2,OY7,24
595742,"Byers, Susan",2017-05-11,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,1SAP2,OY7,24
595743,"Byers, Susan",2017-05-26,BITT SI,7401,403,1SAP2.C.7401.403.3657533,0.00,0.00,0.00,1SAP2,OY7,24
595744,"Byers, Susan",2017-06-21,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.00,0.00,8.00,1SAP2,OY7,24
595745,"Byers, Susan",2017-03-23,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.00,0.00,8.00,1SAP2,OY7,24
595746,"Byers, Susan",2017-03-28,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,1SAP2,OY7,24
595747,"Byers, Susan",2017-03-31,BITT SI,7401,403,1SAP2.C.7401.403.3657533,5.00,0.00,5.00,1SAP2,OY7,24
595748,"Byers, Susan",2017-04-03,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.50,0.00,8.50,1SAP2,OY7,24
595749,"Byers, Susan",2017-04-06,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.00,0.00,8.00,1SAP2,OY7,24
595750,"Byers, Susan",2017-04-11,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,1SAP2,OY7,24
595751,"Byers, Susan",2017-04-12,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,1SAP2,OY7,24
595752,"Byers, Susan",2017-05-12,BITT SI,7401,403,1SAP2.C.7401.403.3657533,3.50,0.00,3.50,1SAP2,OY7,24
595753,"Byers, Susan",2017-05-17,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,1SAP2,OY7,24
595754,"Byers, Susan",2017-05-18,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,1SAP2,OY7,24
595755,"Byers, Susan",2017-05-22,BITT SI,7401,403,1SAP2.C.7401.403.3657533,0.00,0.00,0.00,1SAP2,OY7,24
595756,"Byers, Susan",2017-05-25,BITT SI,7401,403,1SAP2.C.7401.403.3657533,0.00,0.00,0.00,1SAP2,OY7,24
595757,"Byers, Susan",2017-04-18,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,1SAP2,OY7,24
595758,"Byers, Susan",2017-05-05,BITT SI,7401,403,1SAP2.C.7401.403.3657533,3.00,0.00,3.00,1SAP2,OY7,24
595759,"Byers, Susan",2017-05-15,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,1SAP2,OY7,24
595760,"Byers, Susan",2017-06-23,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.00,0.00,8.00,1SAP2,OY7,24
595761,"Byers, Susan",2017-03-21,BITT SI,7401,403,1SAP2.C.7401.403.3657533,4.50,0.00,4.50,1SAP2,OY7,24
595762,"Byers, Susan",2017-03-24,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,1SAP2,OY7,24
595763,"Byers, Susan",2017-04-14,BITT SI,7401,403,1SAP2.C.7401.403.3657533,2.50,0.00,2.50,1SAP2,OY7,24
595764,"Byers, Susan",2017-05-16,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,1SAP2,OY7,24
595765,"Byers, Susan",2017-06-20,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.00,0.00,8.00,1SAP2,OY7,24
595766,"Byers, Susan",2017-03-29,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,1SAP2,OY7,24
595767,"Byers, Susan",2017-04-26,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.50,0.00,8.50,1SAP2,OY7,24

In [398]:
df[(df['ID'] == '1SAP2') & (df['tpid_length'] == 28)]

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,ID,OptYr,tpid_length
10770,"TIMMONS, CARL A",2017-04-26,Install,7420,INS,1SAP2.P.7420.000.3930667.INS,10.00,0.00,10.00,1SAP2,OY7,28
10771,"TIMMONS, CARL A",2017-05-09,Install,7420,INS,1SAP2.P.7420.000.3836553.INS,8.00,0.00,8.00,1SAP2,OY7,28
10772,"TIMMONS, CARL A",2017-05-18,Install,7420,INS,1SAP2.P.7420.000.4230571.INS,5.00,0.00,5.00,1SAP2,OY7,28
10773,"TIMMONS, CARL A",2017-05-30,Install,7420,INS,1SAP2.P.7420.000.4236799.INS,4.00,0.00,4.00,1SAP2,OY7,28
10774,"TIMMONS, CARL A",2017-06-02,Install,7420,INS,1SAP2.P.7420.000.3943423.INS,4.00,0.00,4.00,1SAP2,OY7,28
10775,"TIMMONS, CARL A",2017-06-02,Install,7420,INS,1SAP2.P.7420.000.4234224.INS,2.00,0.00,2.00,1SAP2,OY7,28
10777,"TIMMONS, CARL A",2017-06-20,Install,7420,INS,1SAP2.P.7420.000.4270639.INS,8.00,0.00,8.00,1SAP2,OY7,28
10778,"TIMMONS, CARL A",2017-07-14,Install,7420,INS,1SAP2.P.7420.000.3836565.INS,0.00,8.00,8.00,1SAP2,OY7,28
10779,"TIMMONS, CARL A",2017-07-28,Install,7420,INS,1SAP2.P.7420.000.3836592.INS,8.00,0.00,8.00,1SAP2,OY7,28
10861,"TIMMONS, CARL A",2017-04-13,Install,7420,INS,1SAP2.P.7420.000.3836531.INS,8.00,0.00,8.00,1SAP2,OY7,28
10863,"TIMMONS, CARL A",2017-05-03,1SAP2.P.7420.000.3886270.,7420,INS,1SAP2.P.7420.000.3886270.INS,8.00,0.00,8.00,1SAP2,OY7,28
10864,"TIMMONS, CARL A",2017-05-03,Install,7420,INS,1SAP2.P.7420.000.3943423.INS,2.00,0.00,2.00,1SAP2,OY7,28
10865,"TIMMONS, CARL A",2017-05-18,Install,7420,INS,1SAP2.P.7420.000.4230582.INS,1.00,0.00,1.00,1SAP2,OY7,28
10866,"TIMMONS, CARL A",2017-05-19,Install,7420,INS,1SAP2.P.7420.000.3836565.INS,1.00,0.00,1.00,1SAP2,OY7,28
10867,"TIMMONS, CARL A",2017-05-23,Install,7420,INS,1SAP2.P.7420.000.4230523.INS,2.00,0.00,2.00,1SAP2,OY7,28
10868,"TIMMONS, CARL A",2017-05-30,Install,7420,INS,1SAP2.P.7420.000.3946893.INS,4.00,0.00,4.00,1SAP2,OY7,28
10869,"TIMMONS, CARL A",2017-06-01,Install,7420,INS,1SAP2.P.7420.000.4234224.INS,1.00,0.00,1.00,1SAP2,OY7,28
10870,"TIMMONS, CARL A",2017-06-13,Install,7420,INS,1SAP2.P.7420.000.3836570.INS,7.00,0.00,7.00,1SAP2,OY7,28
10871,"TIMMONS, CARL A",2017-06-15,Install,7420,INS,1SAP2.P.7420.000.3899386.INS,7.00,0.00,7.00,1SAP2,OY7,28
10874,"TIMMONS, CARL A",2017-07-17,1SAP2.P.7420.000.3886270.,7420,INS,1SAP2.P.7420.000.3886270.INS,8.00,0.00,8.00,1SAP2,OY7,28
10875,"TIMMONS, CARL A",2017-07-20,1SAP2.P.7420.000.3886270.,7420,INS,1SAP2.P.7420.000.3886270.INS,8.00,0.00,8.00,1SAP2,OY7,28
10876,"TIMMONS, CARL A",2017-08-01,Install,7420,INS,1SAP2.P.7420.000.4014592.INS,8.00,0.00,8.00,1SAP2,OY7,28
10962,"TIMMONS, CARL A",2017-04-03,Install,7420,INS,1SAP2.P.7420.000.3897825.INS,9.00,0.00,9.00,1SAP2,OY7,28
10963,"TIMMONS, CARL A",2017-04-05,Install,7420,INS,1SAP2.P.7420.000.3958998.INS,8.00,0.00,8.00,1SAP2,OY7,28
10964,"TIMMONS, CARL A",2017-04-12,Install,7420,INS,1SAP2.P.7420.000.3836531.INS,8.00,0.00,8.00,1SAP2,OY7,28
10965,"TIMMONS, CARL A",2017-04-14,Install,7420,INS,1SAP2.P.7420.000.3836531.INS,0.00,0.00,0.00,1SAP2,OY7,28
10967,"TIMMONS, CARL A",2017-05-11,Install,7420,INS,1SAP2.P.7420.000.4033685.INS,4.00,0.00,4.00,1SAP2,OY7,28
10969,"TIMMONS, CARL A",2017-05-18,Install,7420,INS,1SAP2.P.7420.000.4234224.INS,4.00,0.00,4.00,1SAP2,OY7,28
10970,"TIMMONS, CARL A",2017-05-24,Install,7420,INS,1SAP2.P.7420.000.4230523.INS,10.00,0.00,10.00,1SAP2,OY7,28
10971,"TIMMONS, CARL A",2017-05-26,Install,7420,INS,1SAP2.P.7420.000.3836565.INS,3.00,0.00,3.00,1SAP2,OY7,28
...,...,...,...,...,...,...,...,...,...,...,...,...
595483,"Motley, Michael",2017-05-04,DSPM,7420,DPM,1SAP2.P.7420.000.4209514.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595484,"Motley, Michael",2017-05-10,DSPM,7420,DPM,1SAP2.P.7420.000.4209514.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595485,"Motley, Michael",2017-05-11,DSPM,7420,DPM,1SAP2.P.7420.000.3897287.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595486,"Motley, Michael",2017-05-16,DSPM,7420,DPM,1SAP2.P.7420.000.4209514.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595487,"Motley, Michael",2017-05-18,DSPM,7420,DPM,1SAP2.P.7420.000.4192994.DPM,0.30,0.00,0.30,1SAP2,OY7,28
595493,"Motley, Michael",2017-04-04,DSPM,7420,DPM,1SAP2.P.7420.000.3965816.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595494,"Motley, Michael",2017-04-04,DSPM,7420,DPM,1SAP2.P.7420.000.4074003.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595497,"Motley, Michael",2017-04-17,DSPM,7420,DPM,1SAP2.P.7420.000.4074003.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595499,"Motley, Michael",2017-04-25,DSPM,7420,DPM,1SAP2.P.7420.000.4101063.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595500,"Motley, Michael",2017-04-27,DSPM,7420,DPM,1SAP2.P.7420.000.4131520.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595501,"Motley, Michael",2017-05-08,DSPM,7420,DPM,1SAP2.P.7420.000.4101063.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595502,"Motley, Michael",2017-05-11,DSPM,7420,DPM,1SAP2.P.7420.000.3843353.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595503,"Motley, Michael",2017-05-18,DSPM,7420,DPM,1SAP2.P.7420.000.3843353.DPM,0.30,0.00,0.30,1SAP2,OY7,28
595504,"Motley, Michael",2017-03-21,DSPM,7420,DPM,1SAP2.P.7420.000.4114925.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595507,"Motley, Michael",2017-04-12,DSPM,7420,DPM,1SAP2.P.7420.000.4124441.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595510,"Motley, Michael",2017-04-28,DSPM,7420,DPM,1SAP2.P.7420.000.4172460.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595512,"Motley, Michael",2017-05-16,DSPM,7420,DPM,1SAP2.P.7420.000.3843353.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595513,"Motley, Michael",2017-05-18,DSPM,7420,DPM,1SAP2.P.7420.000.4131520.DPM,0.30,0.00,0.30,1SAP2,OY7,28
595515,"Motley, Michael",2017-03-29,DSPM,7420,DPM,1SAP2.P.7420.000.3965816.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595516,"Motley, Michael",2017-03-29,DSPM,7420,DPM,1SAP2.P.7420.000.4129143.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595519,"Motley, Michael",2017-04-13,DSPM,7420,DPM,1SAP2.P.7420.000.4044894.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595522,"Motley, Michael",2017-05-02,DSPM,7420,DPM,1SAP2.P.7420.000.4167563.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595523,"Motley, Michael",2017-05-04,DSPM,7420,DPM,1SAP2.P.7420.000.3965816.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595525,"Motley, Michael",2017-05-08,DSPM,7420,DPM,1SAP2.P.7420.000.4172460.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595527,"Motley, Michael",2017-04-05,DSPM,7420,DPM,1SAP2.P.7420.000.4129143.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595529,"Motley, Michael",2017-04-18,DSPM,7420,DPM,1SAP2.P.7420.000.4172460.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595532,"Motley, Michael",2017-05-03,DSPM,7420,DPM,1SAP2.P.7420.000.4172460.DPM,1.00,0.00,1.00,1SAP2,OY7,28
595533,"Motley, Michael",2017-05-08,DSPM,7420,DPM,1SAP2.P.7420.000.4131520.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595534,"Motley, Michael",2017-05-10,DSPM,7420,DPM,1SAP2.P.7420.000.3916488.DPM,0.50,0.00,0.50,1SAP2,OY7,28
595535,"Motley, Michael",2017-05-18,DSPM,7420,DPM,1SAP2.P.7420.000.3897287.DPM,0.30,0.00,0.30,1SAP2,OY7,28

In [399]:
# count number of rows associated with different character count lengths of tpid
df['tpid_length'].value_counts()

24    298818
16    287456
28      9573
17         3
Name: tpid_length, dtype: int64

In [210]:
df[df['tpid_length'] == 17]

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length
544186,"Wali, Sam",2019-02-27,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17
544187,"Wali, Sam",2019-03-01,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17
544188,"Wali, Sam",2019-02-28,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17

In [211]:
# break dataframe into parts based on length of tpid
df16 = df[df['tpid_length'] == 16]
df17 = df[df['tpid_length'] == 17]
df24 = df[df['tpid_length'] == 24]
df28 = df[df['tpid_length'] == 28]
del[df]
gc.collect()

496

In [212]:
df16

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,OY7,16
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,OY7,16
3,"THOMPSON, MORRIS R",2017-08-10,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
4,"THOMPSON, MORRIS R",2017-08-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
5,"THOMPSON, MORRIS R",2017-09-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
6,"THOMPSON, MORRIS R",2017-09-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
7,"THOMPSON, MORRIS R",2017-09-21,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
8,"THOMPSON, MORRIS R",2017-09-25,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
9,"THOMPSON, MORRIS R",2017-10-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
10,"THOMPSON, MORRIS R",2017-10-27,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
11,"THOMPSON, MORRIS R",2017-10-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
12,"THOMPSON, MORRIS R",2017-11-02,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
13,"THOMPSON, MORRIS R",2017-11-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
14,"THOMPSON, MORRIS R",2017-11-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
15,"THOMPSON, MORRIS R",2017-11-17,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
16,"THOMPSON, MORRIS R",2017-11-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
17,"THOMPSON, MORRIS R",2017-11-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
18,"THOMPSON, MORRIS R",2017-11-29,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
19,"THOMPSON, MORRIS R",2017-12-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
20,"THOMPSON, MORRIS R",2018-01-16,Asset Management,8400,514,1SAP2.C.8400.514,4.00,0.00,4.00,OY8,16
21,"THOMPSON, MORRIS R",2018-01-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
22,"THOMPSON, MORRIS R",2018-02-12,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
23,"THOMPSON, MORRIS R",2018-02-20,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00,OY8,16
24,"THOMPSON, MORRIS R",2018-02-23,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00,OY8,16
25,"THOMPSON, MORRIS R",2018-02-23,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,OY8,16
26,"THOMPSON, MORRIS R",2018-03-05,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
27,"THOMPSON, MORRIS R",2018-03-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16
28,"THOMPSON, MORRIS R",2018-03-07,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,OY8,16
29,"THOMPSON, MORRIS R",2018-03-16,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00,OY8,16
30,"THOMPSON, MORRIS R",2018-03-23,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,7.50,0.00,7.50,OY8,16
...,...,...,...,...,...,...,...,...,...,...,...
595820,"Simmons, Kenneth",2017-05-02,D Mission Support,7300,683,1SAP2.C.7300.683,9.00,0.00,9.00,OY7,16
595821,"Simmons, Kenneth",2017-05-09,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,OY7,16
595822,"Simmons, Kenneth",2017-05-18,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,OY7,16
595823,"Simmons, Kenneth",2017-06-27,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,OY7,16
595824,"Simmons, Kenneth",2017-06-28,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,OY7,16
595825,"Simmons, Kenneth",2017-07-03,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50,OY7,16
595826,"Simmons, Kenneth",2017-07-05,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00,OY7,16
595827,"Simmons, Kenneth",2017-07-08,D Mission Support,7300,683,1SAP2.C.7300.683,4.50,0.00,4.50,OY7,16
595828,"Simmons, Kenneth",2017-03-29,D Mission Support,7300,683,1SAP2.C.7300.683,7.50,0.00,7.50,OY7,16
595829,"Simmons, Kenneth",2017-04-06,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00,OY7,16
595830,"Simmons, Kenneth",2017-04-19,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,OY7,16
595831,"Simmons, Kenneth",2017-04-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,OY7,16
595832,"Simmons, Kenneth",2017-04-26,D Mission Support,7300,683,1SAP2.C.7300.683,9.50,0.00,9.50,OY7,16
595833,"Simmons, Kenneth",2017-05-05,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,OY7,16
595834,"Simmons, Kenneth",2017-05-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,OY7,16
595835,"Simmons, Kenneth",2017-05-31,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,OY7,16
595836,"Simmons, Kenneth",2017-06-06,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,OY7,16
595837,"Simmons, Kenneth",2017-06-18,D Mission Support,7300,683,1SAP2.C.7300.683,13.00,0.00,13.00,OY7,16
595838,"Simmons, Kenneth",2017-06-21,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,OY7,16
595839,"Simmons, Kenneth",2017-07-10,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,OY7,16
595840,"Simmons, Kenneth",2017-07-13,D Mission Support,7300,683,1SAP2.C.7300.683,3.50,0.00,3.50,OY7,16
595841,"Simmons, Kenneth",2017-03-20,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,OY7,16
595842,"Simmons, Kenneth",2017-03-23,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00,OY7,16
595843,"Simmons, Kenneth",2017-03-27,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00,OY7,16
595844,"Simmons, Kenneth",2017-04-17,D Mission Support,7300,683,1SAP2.C.7300.683,6.00,0.00,6.00,OY7,16
595845,"Simmons, Kenneth",2017-05-07,D Mission Support,7300,683,1SAP2.C.7300.683,14.00,0.00,14.00,OY7,16
595846,"Simmons, Kenneth",2017-05-10,D Mission Support,7300,683,1SAP2.C.7300.683,11.50,0.00,11.50,OY7,16
595847,"Simmons, Kenneth",2017-06-13,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50,OY7,16
595848,"Simmons, Kenneth",2017-07-06,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00,OY7,16
595849,"Simmons, Kenneth",2017-07-19,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50,OY7,16

In [213]:
df17

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length
544186,"Wali, Sam",2019-02-27,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17
544187,"Wali, Sam",2019-03-01,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17
544188,"Wali, Sam",2019-02-28,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17

In [214]:
df24

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,OY7,24
56,"THOMPSON, MORRIS R",2017-07-11,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,OY7,24
57,"THOMPSON, MORRIS R",2017-07-18,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,OY7,24
127,"THOMPSON, MORRIS R",2017-07-17,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,OY7,24
129,"THOMPSON, MORRIS R",2017-07-20,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,OY7,24
190,"THOMPSON, MORRIS R",2017-07-13,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,OY7,24
256,"THOMPSON, MORRIS R",2017-07-12,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,OY7,24
397,"THOMPSON, MORRIS R",2017-07-14,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,OY7,24
545,"BROWN, AUSTIN",2018-05-14,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,3.00,0.00,3.00,OY8,24
546,"BROWN, AUSTIN",2018-05-23,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,8.00,0.00,8.00,OY8,24
547,"BROWN, AUSTIN",2018-05-23,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,8.00,0.00,8.00,OY8,24
548,"BROWN, AUSTIN",2018-05-30,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,8.00,0.00,8.00,OY8,24
549,"BROWN, AUSTIN",2018-06-12,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,11.00,0.00,11.00,OY8,24
550,"BROWN, AUSTIN",2018-06-14,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,8.00,0.00,8.00,OY8,24
551,"BROWN, AUSTIN",2018-06-18,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,0.00,0.00,0.00,OY8,24
552,"BROWN, AUSTIN",2018-06-21,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,0.00,0.00,0.00,OY8,24
553,"BROWN, AUSTIN",2018-06-28,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,0.00,0.00,0.00,OY8,24
554,"BROWN, AUSTIN",2018-07-03,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,-8.00,0.00,-8.00,OY8,24
555,"BROWN, AUSTIN",2018-07-06,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,-6.00,0.00,-6.00,OY8,24
556,"BROWN, AUSTIN",2018-07-11,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,6.00,0.00,6.00,OY8,24
557,"BROWN, AUSTIN",2018-07-13,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,8.00,0.00,8.00,OY8,24
558,"BROWN, AUSTIN",2018-07-18,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,5.00,0.00,5.00,OY8,24
559,"BROWN, AUSTIN",2018-07-24,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,6.50,0.00,6.50,OY8,24
560,"BROWN, AUSTIN",2018-07-26,MGMADM,8330,000,1SAP2.F.8330.000.MGTMADM,6.50,0.00,6.50,OY8,24
561,"BROWN, AUSTIN",2018-07-27,1SAP2.F.8330.000.0DCSPRS,8330,000,1SAP2.F.8330.000.0DCSPRS,8.00,0.00,8.00,OY8,24
562,"BROWN, AUSTIN",2018-08-16,MGMADM,9330,000,1SAP2.F.9330.000.MGTMADM,9.00,0.00,9.00,OY9,24
563,"BROWN, AUSTIN",2018-08-28,MGMADM,9330,000,1SAP2.F.9330.000.MGTMADM,0.00,0.00,0.00,OY9,24
564,"BROWN, AUSTIN",2018-08-31,MGMADM,9330,000,1SAP2.F.9330.000.MGTMADM,0.00,0.00,0.00,OY9,24
565,"BROWN, AUSTIN",2018-10-05,MGMADM,9330,000,1SAP2.F.9330.000.MGTMADM,0.00,0.00,0.00,OY9,24
566,"BROWN, AUSTIN",2018-10-10,MGMADM,9330,000,1SAP2.F.9330.000.MGTMADM,0.00,0.00,0.00,OY9,24
...,...,...,...,...,...,...,...,...,...,...,...
595738,"Byers, Susan",2017-05-03,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.50,0.00,8.50,OY7,24
595739,"Byers, Susan",2017-05-04,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,OY7,24
595740,"Byers, Susan",2017-05-09,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,OY7,24
595741,"Byers, Susan",2017-05-10,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,OY7,24
595742,"Byers, Susan",2017-05-11,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,OY7,24
595743,"Byers, Susan",2017-05-26,BITT SI,7401,403,1SAP2.C.7401.403.3657533,0.00,0.00,0.00,OY7,24
595744,"Byers, Susan",2017-06-21,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.00,0.00,8.00,OY7,24
595745,"Byers, Susan",2017-03-23,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.00,0.00,8.00,OY7,24
595746,"Byers, Susan",2017-03-28,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,OY7,24
595747,"Byers, Susan",2017-03-31,BITT SI,7401,403,1SAP2.C.7401.403.3657533,5.00,0.00,5.00,OY7,24
595748,"Byers, Susan",2017-04-03,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.50,0.00,8.50,OY7,24
595749,"Byers, Susan",2017-04-06,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.00,0.00,8.00,OY7,24
595750,"Byers, Susan",2017-04-11,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,OY7,24
595751,"Byers, Susan",2017-04-12,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,OY7,24
595752,"Byers, Susan",2017-05-12,BITT SI,7401,403,1SAP2.C.7401.403.3657533,3.50,0.00,3.50,OY7,24
595753,"Byers, Susan",2017-05-17,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,OY7,24
595754,"Byers, Susan",2017-05-18,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,OY7,24
595755,"Byers, Susan",2017-05-22,BITT SI,7401,403,1SAP2.C.7401.403.3657533,0.00,0.00,0.00,OY7,24
595756,"Byers, Susan",2017-05-25,BITT SI,7401,403,1SAP2.C.7401.403.3657533,0.00,0.00,0.00,OY7,24
595757,"Byers, Susan",2017-04-18,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,OY7,24
595758,"Byers, Susan",2017-05-05,BITT SI,7401,403,1SAP2.C.7401.403.3657533,3.00,0.00,3.00,OY7,24
595759,"Byers, Susan",2017-05-15,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,OY7,24
595760,"Byers, Susan",2017-06-23,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.00,0.00,8.00,OY7,24
595761,"Byers, Susan",2017-03-21,BITT SI,7401,403,1SAP2.C.7401.403.3657533,4.50,0.00,4.50,OY7,24
595762,"Byers, Susan",2017-03-24,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,OY7,24
595763,"Byers, Susan",2017-04-14,BITT SI,7401,403,1SAP2.C.7401.403.3657533,2.50,0.00,2.50,OY7,24
595764,"Byers, Susan",2017-05-16,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.50,0.00,9.50,OY7,24
595765,"Byers, Susan",2017-06-20,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.00,0.00,8.00,OY7,24
595766,"Byers, Susan",2017-03-29,BITT SI,7401,403,1SAP2.C.7401.403.3657533,9.00,0.00,9.00,OY7,24
595767,"Byers, Susan",2017-04-26,BITT SI,7401,403,1SAP2.C.7401.403.3657533,8.50,0.00,8.50,OY7,24

In [215]:
df28

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length
10770,"TIMMONS, CARL A",2017-04-26,Install,7420,INS,1SAP2.P.7420.000.3930667.INS,10.00,0.00,10.00,OY7,28
10771,"TIMMONS, CARL A",2017-05-09,Install,7420,INS,1SAP2.P.7420.000.3836553.INS,8.00,0.00,8.00,OY7,28
10772,"TIMMONS, CARL A",2017-05-18,Install,7420,INS,1SAP2.P.7420.000.4230571.INS,5.00,0.00,5.00,OY7,28
10773,"TIMMONS, CARL A",2017-05-30,Install,7420,INS,1SAP2.P.7420.000.4236799.INS,4.00,0.00,4.00,OY7,28
10774,"TIMMONS, CARL A",2017-06-02,Install,7420,INS,1SAP2.P.7420.000.3943423.INS,4.00,0.00,4.00,OY7,28
10775,"TIMMONS, CARL A",2017-06-02,Install,7420,INS,1SAP2.P.7420.000.4234224.INS,2.00,0.00,2.00,OY7,28
10777,"TIMMONS, CARL A",2017-06-20,Install,7420,INS,1SAP2.P.7420.000.4270639.INS,8.00,0.00,8.00,OY7,28
10778,"TIMMONS, CARL A",2017-07-14,Install,7420,INS,1SAP2.P.7420.000.3836565.INS,0.00,8.00,8.00,OY7,28
10779,"TIMMONS, CARL A",2017-07-28,Install,7420,INS,1SAP2.P.7420.000.3836592.INS,8.00,0.00,8.00,OY7,28
10861,"TIMMONS, CARL A",2017-04-13,Install,7420,INS,1SAP2.P.7420.000.3836531.INS,8.00,0.00,8.00,OY7,28
10863,"TIMMONS, CARL A",2017-05-03,1SAP2.P.7420.000.3886270.,7420,INS,1SAP2.P.7420.000.3886270.INS,8.00,0.00,8.00,OY7,28
10864,"TIMMONS, CARL A",2017-05-03,Install,7420,INS,1SAP2.P.7420.000.3943423.INS,2.00,0.00,2.00,OY7,28
10865,"TIMMONS, CARL A",2017-05-18,Install,7420,INS,1SAP2.P.7420.000.4230582.INS,1.00,0.00,1.00,OY7,28
10866,"TIMMONS, CARL A",2017-05-19,Install,7420,INS,1SAP2.P.7420.000.3836565.INS,1.00,0.00,1.00,OY7,28
10867,"TIMMONS, CARL A",2017-05-23,Install,7420,INS,1SAP2.P.7420.000.4230523.INS,2.00,0.00,2.00,OY7,28
10868,"TIMMONS, CARL A",2017-05-30,Install,7420,INS,1SAP2.P.7420.000.3946893.INS,4.00,0.00,4.00,OY7,28
10869,"TIMMONS, CARL A",2017-06-01,Install,7420,INS,1SAP2.P.7420.000.4234224.INS,1.00,0.00,1.00,OY7,28
10870,"TIMMONS, CARL A",2017-06-13,Install,7420,INS,1SAP2.P.7420.000.3836570.INS,7.00,0.00,7.00,OY7,28
10871,"TIMMONS, CARL A",2017-06-15,Install,7420,INS,1SAP2.P.7420.000.3899386.INS,7.00,0.00,7.00,OY7,28
10874,"TIMMONS, CARL A",2017-07-17,1SAP2.P.7420.000.3886270.,7420,INS,1SAP2.P.7420.000.3886270.INS,8.00,0.00,8.00,OY7,28
10875,"TIMMONS, CARL A",2017-07-20,1SAP2.P.7420.000.3886270.,7420,INS,1SAP2.P.7420.000.3886270.INS,8.00,0.00,8.00,OY7,28
10876,"TIMMONS, CARL A",2017-08-01,Install,7420,INS,1SAP2.P.7420.000.4014592.INS,8.00,0.00,8.00,OY7,28
10962,"TIMMONS, CARL A",2017-04-03,Install,7420,INS,1SAP2.P.7420.000.3897825.INS,9.00,0.00,9.00,OY7,28
10963,"TIMMONS, CARL A",2017-04-05,Install,7420,INS,1SAP2.P.7420.000.3958998.INS,8.00,0.00,8.00,OY7,28
10964,"TIMMONS, CARL A",2017-04-12,Install,7420,INS,1SAP2.P.7420.000.3836531.INS,8.00,0.00,8.00,OY7,28
10965,"TIMMONS, CARL A",2017-04-14,Install,7420,INS,1SAP2.P.7420.000.3836531.INS,0.00,0.00,0.00,OY7,28
10967,"TIMMONS, CARL A",2017-05-11,Install,7420,INS,1SAP2.P.7420.000.4033685.INS,4.00,0.00,4.00,OY7,28
10969,"TIMMONS, CARL A",2017-05-18,Install,7420,INS,1SAP2.P.7420.000.4234224.INS,4.00,0.00,4.00,OY7,28
10970,"TIMMONS, CARL A",2017-05-24,Install,7420,INS,1SAP2.P.7420.000.4230523.INS,10.00,0.00,10.00,OY7,28
10971,"TIMMONS, CARL A",2017-05-26,Install,7420,INS,1SAP2.P.7420.000.3836565.INS,3.00,0.00,3.00,OY7,28
...,...,...,...,...,...,...,...,...,...,...,...
595483,"Motley, Michael",2017-05-04,DSPM,7420,DPM,1SAP2.P.7420.000.4209514.DPM,0.50,0.00,0.50,OY7,28
595484,"Motley, Michael",2017-05-10,DSPM,7420,DPM,1SAP2.P.7420.000.4209514.DPM,1.00,0.00,1.00,OY7,28
595485,"Motley, Michael",2017-05-11,DSPM,7420,DPM,1SAP2.P.7420.000.3897287.DPM,0.50,0.00,0.50,OY7,28
595486,"Motley, Michael",2017-05-16,DSPM,7420,DPM,1SAP2.P.7420.000.4209514.DPM,0.50,0.00,0.50,OY7,28
595487,"Motley, Michael",2017-05-18,DSPM,7420,DPM,1SAP2.P.7420.000.4192994.DPM,0.30,0.00,0.30,OY7,28
595493,"Motley, Michael",2017-04-04,DSPM,7420,DPM,1SAP2.P.7420.000.3965816.DPM,0.50,0.00,0.50,OY7,28
595494,"Motley, Michael",2017-04-04,DSPM,7420,DPM,1SAP2.P.7420.000.4074003.DPM,0.50,0.00,0.50,OY7,28
595497,"Motley, Michael",2017-04-17,DSPM,7420,DPM,1SAP2.P.7420.000.4074003.DPM,1.00,0.00,1.00,OY7,28
595499,"Motley, Michael",2017-04-25,DSPM,7420,DPM,1SAP2.P.7420.000.4101063.DPM,0.50,0.00,0.50,OY7,28
595500,"Motley, Michael",2017-04-27,DSPM,7420,DPM,1SAP2.P.7420.000.4131520.DPM,1.00,0.00,1.00,OY7,28
595501,"Motley, Michael",2017-05-08,DSPM,7420,DPM,1SAP2.P.7420.000.4101063.DPM,0.50,0.00,0.50,OY7,28
595502,"Motley, Michael",2017-05-11,DSPM,7420,DPM,1SAP2.P.7420.000.3843353.DPM,1.00,0.00,1.00,OY7,28
595503,"Motley, Michael",2017-05-18,DSPM,7420,DPM,1SAP2.P.7420.000.3843353.DPM,0.30,0.00,0.30,OY7,28
595504,"Motley, Michael",2017-03-21,DSPM,7420,DPM,1SAP2.P.7420.000.4114925.DPM,0.50,0.00,0.50,OY7,28
595507,"Motley, Michael",2017-04-12,DSPM,7420,DPM,1SAP2.P.7420.000.4124441.DPM,0.50,0.00,0.50,OY7,28
595510,"Motley, Michael",2017-04-28,DSPM,7420,DPM,1SAP2.P.7420.000.4172460.DPM,0.50,0.00,0.50,OY7,28
595512,"Motley, Michael",2017-05-16,DSPM,7420,DPM,1SAP2.P.7420.000.3843353.DPM,1.00,0.00,1.00,OY7,28
595513,"Motley, Michael",2017-05-18,DSPM,7420,DPM,1SAP2.P.7420.000.4131520.DPM,0.30,0.00,0.30,OY7,28
595515,"Motley, Michael",2017-03-29,DSPM,7420,DPM,1SAP2.P.7420.000.3965816.DPM,1.00,0.00,1.00,OY7,28
595516,"Motley, Michael",2017-03-29,DSPM,7420,DPM,1SAP2.P.7420.000.4129143.DPM,1.00,0.00,1.00,OY7,28
595519,"Motley, Michael",2017-04-13,DSPM,7420,DPM,1SAP2.P.7420.000.4044894.DPM,0.50,0.00,0.50,OY7,28
595522,"Motley, Michael",2017-05-02,DSPM,7420,DPM,1SAP2.P.7420.000.4167563.DPM,1.00,0.00,1.00,OY7,28
595523,"Motley, Michael",2017-05-04,DSPM,7420,DPM,1SAP2.P.7420.000.3965816.DPM,1.00,0.00,1.00,OY7,28
595525,"Motley, Michael",2017-05-08,DSPM,7420,DPM,1SAP2.P.7420.000.4172460.DPM,0.50,0.00,0.50,OY7,28
595527,"Motley, Michael",2017-04-05,DSPM,7420,DPM,1SAP2.P.7420.000.4129143.DPM,1.00,0.00,1.00,OY7,28
595529,"Motley, Michael",2017-04-18,DSPM,7420,DPM,1SAP2.P.7420.000.4172460.DPM,0.50,0.00,0.50,OY7,28
595532,"Motley, Michael",2017-05-03,DSPM,7420,DPM,1SAP2.P.7420.000.4172460.DPM,1.00,0.00,1.00,OY7,28
595533,"Motley, Michael",2017-05-08,DSPM,7420,DPM,1SAP2.P.7420.000.4131520.DPM,0.50,0.00,0.50,OY7,28
595534,"Motley, Michael",2017-05-10,DSPM,7420,DPM,1SAP2.P.7420.000.3916488.DPM,0.50,0.00,0.50,OY7,28
595535,"Motley, Michael",2017-05-18,DSPM,7420,DPM,1SAP2.P.7420.000.3897287.DPM,0.30,0.00,0.30,OY7,28

In [157]:
df17.shape

(3, 11)

In [ ]:
# see which id have 17 tpid characters
df17['ID'].value_counts()

In [158]:
# insert SR_prefix column
df17.insert(1, 'SR_prefix', 'SR-')
df17

,User,SR_prefix,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length
544186,"Wali, Sam",SR-,2019-02-27,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17
544187,"Wali, Sam",SR-,2019-03-01,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17
544188,"Wali, Sam",SR-,2019-02-28,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17

In [159]:
# insert SR_no column
df17['SR_no'] = df17.TPID.str.split(".", expand=True,)[2]
df17

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,User,SR_prefix,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length,SR_no
544186,"Wali, Sam",SR-,2019-02-27,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17,3873257
544187,"Wali, Sam",SR-,2019-03-01,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17,3873257
544188,"Wali, Sam",SR-,2019-02-28,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17,3873257

In [160]:
df17['SR'] = df17['SR_prefix'] + df17['SR_no']
df17

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

,User,SR_prefix,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length,SR_no,SR
544186,"Wali, Sam",SR-,2019-02-27,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17,3873257,SR-3873257
544187,"Wali, Sam",SR-,2019-03-01,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17,3873257,SR-3873257
544188,"Wali, Sam",SR-,2019-02-28,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17,3873257,SR-3873257

In [161]:
df17 = df17.drop('SR_no', 1)
df17 = df17.drop('SR_prefix', 1)
df17

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length,SR
544186,"Wali, Sam",2019-02-27,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17,SR-3873257
544187,"Wali, Sam",2019-03-01,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17,SR-3873257
544188,"Wali, Sam",2019-02-28,1s10p.174.3873257,4.38,325,1S10P.174.3873257,0.00,0.00,0.00,OY9,17,SR-3873257

In [162]:
df16.head(3)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,OY7,16
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,OY7,16
3,"THOMPSON, MORRIS R",2017-08-10,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16

In [163]:
df16.shape

(287456, 11)

In [164]:
# insert SR_prefix column
df16.insert(1, 'SR', 'SR-0000000')
df16.head(3)

,User,SR,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length
1,"THOMPSON, MORRIS R",SR-0000000,2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,OY7,16
2,"THOMPSON, MORRIS R",SR-0000000,2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00,OY7,16
3,"THOMPSON, MORRIS R",SR-0000000,2017-08-10,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00,OY8,16

In [165]:
df24.head(3)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00,OY7,24
56,"THOMPSON, MORRIS R",2017-07-11,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,OY7,24
57,"THOMPSON, MORRIS R",2017-07-18,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00,OY7,24

In [166]:
df28.shape

(9573, 11)

In [167]:
# insert SR_prefix column
df28.insert(1, 'SR_prefix', 'SR-')
df28.head(3)

,User,SR_prefix,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length
10770,"TIMMONS, CARL A",SR-,2017-04-26,Install,7420,INS,1SAP2.P.7420.000.3930667.INS,10.00,0.00,10.00,OY7,28
10771,"TIMMONS, CARL A",SR-,2017-05-09,Install,7420,INS,1SAP2.P.7420.000.3836553.INS,8.00,0.00,8.00,OY7,28
10772,"TIMMONS, CARL A",SR-,2017-05-18,Install,7420,INS,1SAP2.P.7420.000.4230571.INS,5.00,0.00,5.00,OY7,28

In [168]:
# insert SR_no column
df28['SR_no'] = df28.TPID.str.split(".", expand=True,)[4]
df28.head

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,User,SR_prefix,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length,SR_no
10770,"TIMMONS, CARL A",SR-,2017-04-26,Install,7420,INS,1SAP2.P.7420.000.3930667.INS,10.00,0.00,10.00,OY7,28,3930667
10771,"TIMMONS, CARL A",SR-,2017-05-09,Install,7420,INS,1SAP2.P.7420.000.3836553.INS,8.00,0.00,8.00,OY7,28,3836553
10772,"TIMMONS, CARL A",SR-,2017-05-18,Install,7420,INS,1SAP2.P.7420.000.4230571.INS,5.00,0.00,5.00,OY7,28,4230571

In [169]:
df28['SR'] = df28['SR_prefix'] + df28['SR_no']
df28.head(3)

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

,User,SR_prefix,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length,SR_no,SR
10770,"TIMMONS, CARL A",SR-,2017-04-26,Install,7420,INS,1SAP2.P.7420.000.3930667.INS,10.00,0.00,10.00,OY7,28,3930667,SR-3930667
10771,"TIMMONS, CARL A",SR-,2017-05-09,Install,7420,INS,1SAP2.P.7420.000.3836553.INS,8.00,0.00,8.00,OY7,28,3836553,SR-3836553
10772,"TIMMONS, CARL A",SR-,2017-05-18,Install,7420,INS,1SAP2.P.7420.000.4230571.INS,5.00,0.00,5.00,OY7,28,4230571,SR-4230571

In [170]:
df28 = df28.drop('SR_no', 1)
df28 = df28.drop('SR_prefix', 1)
df28.head(3)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,OptYr,tpid_length,SR
10770,"TIMMONS, CARL A",2017-04-26,Install,7420,INS,1SAP2.P.7420.000.3930667.INS,10.00,0.00,10.00,OY7,28,SR-3930667
10771,"TIMMONS, CARL A",2017-05-09,Install,7420,INS,1SAP2.P.7420.000.3836553.INS,8.00,0.00,8.00,OY7,28,SR-3836553
10772,"TIMMONS, CARL A",2017-05-18,Install,7420,INS,1SAP2.P.7420.000.4230571.INS,5.00,0.00,5.00,OY7,28,SR-4230571

In [173]:
df16.columns

Index(['User', 'Work Date', 'Description', 'CLIN', 'WBS', 'TPID', 'Straight',
       'Overtime', 'Total', 'SR', 'OptYr', 'tpid_length'],
      dtype='object')

In [174]:
df17.columns

Index(['User', 'Work Date', 'Description', 'CLIN', 'WBS', 'TPID', 'Straight',
       'Overtime', 'Total', 'SR', 'OptYr', 'tpid_length'],
      dtype='object')

In [175]:
df24.columns

Index(['User', 'Work Date', 'Description', 'CLIN', 'WBS', 'TPID', 'Straight',
       'Overtime', 'Total', 'OptYr', 'tpid_length'],
      dtype='object')

In [176]:
df28.columns

Index(['User', 'Work Date', 'Description', 'CLIN', 'WBS', 'TPID', 'Straight',
       'Overtime', 'Total', 'OptYr', 'tpid_length', 'SR'],
      dtype='object')

In [171]:
# standardize column order
df16 = df16[['User', 'Work Date', 'Description', 'CLIN', 'WBS', 'TPID', 'Straight', 'Overtime', 'Total', 'SR', 'OptYr', 'tpid_length']]
df17 = df17[['User', 'Work Date', 'Description', 'CLIN', 'WBS', 'TPID', 'Straight', 'Overtime', 'Total', 'SR', 'OptYr', 'tpid_length']]
df24 = df24[['User', 'Work Date', 'Description', 'CLIN', 'WBS', 'TPID', 'Straight', 'Overtime', 'Total', 'SR', 'OptYr', 'tpid_length']]
df28 = df28[['User', 'Work Date', 'Description', 'CLIN', 'WBS', 'TPID', 'Straight', 'Overtime', 'Total', 'SR', 'OptYr', 'tpid_length']]

KeyError: "['SR'] not in index"

In [ ]:
df16.head(3)

In [ ]:
df17.head(3)

In [ ]:
df20.head(3)

In [ ]:
df28.head(3)

In [ ]:
# concatenate vertical dataframes
df = pandas.concat([df16, df17, df20, df28], axis=0)

In [48]:
# concatenate vertical dataframes
df = pandas.concat([df20, df28], axis=0)

In [49]:
df20.shape

(185633, 12)

In [50]:
df28.shape

(38891, 12)

In [51]:
# check columns
df.shape

(224524, 12)

In [52]:
del[df20, df28]

In [53]:
gc.collect()

300

In [54]:
# write data to csv (default is U:\Documents)
df.to_csv('AP2 Regular & OT Hours for Adv by CCC_#505ap-modified.csv')

In [55]:
# check metadata
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 224524 entries, 0 to 224482
Data columns (total 12 columns):
User           224524 non-null object
Work Date      224524 non-null object
Description    224524 non-null object
CLIN           224524 non-null object
WBS            224524 non-null object
TPID           224524 non-null object
Straight       224524 non-null float64
Overtime       224524 non-null float64
Total          224524 non-null float64
SR             224524 non-null object
OptYr          224524 non-null object
tpid_length    224524 non-null int64
dtypes: float64(3), int64(1), object(8)
memory usage: 22.3+ MB

In [56]:
# data check
df.head(3)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,SR,OptYr,tpid_length
0,"SCHNEIDER, LAURA E",2020-07-14,Standby Only - COVID-19,0111,999,13976.00.01.0111.999,0.00,0.00,0.00,SR-0000000,OY.,20
1,"SCHNEIDER, LAURA E",2020-07-17,Standby Only - COVID-19,0111,999,13976.00.01.0111.999,0.00,0.00,0.00,SR-0000000,OY.,20
2,"SCHNEIDER, LAURA E",2020-07-20,Standby Only - COVID-19,0111,999,13976.00.01.0111.999,8.00,0.00,8.00,SR-0000000,OY.,20

In [57]:
# tip 1
# create dataframe with mixed data types
pandas.util.testing.makeMixedDataFrame()

     A    B     C          D
0 0.00 0.00  foo1 2009-01-01
1 1.00 1.00  foo2 2009-01-02
2 2.00 0.00  foo3 2009-01-05
3 3.00 1.00  foo4 2009-01-06
4 4.00 0.00  foo5 2009-01-07

In [58]:
# tip 2
# insert a new column which is a function of another column
dftest = pandas.util.testing.makeMixedDataFrame()
#print(dftest)
dftest.insert(3, 'A2', dftest['A'] * 2)
dftest

     A    B     C   A2          D
0 0.00 0.00  foo1 0.00 2009-01-01
1 1.00 1.00  foo2 2.00 2009-01-02
2 2.00 0.00  foo3 4.00 2009-01-05
3 3.00 1.00  foo4 6.00 2009-01-06
4 4.00 0.00  foo5 8.00 2009-01-07

In [59]:
# tip 3
# insert a new column with a constant value in the column with index 3 (i.e., 4)
dftest = pandas.util.testing.makeMixedDataFrame()
dftest.insert(3, 'Country', 'USA')
dftest

     A    B     C Country          D
0 0.00 0.00  foo1     USA 2009-01-01
1 1.00 1.00  foo2     USA 2009-01-02
2 2.00 0.00  foo3     USA 2009-01-05
3 3.00 1.00  foo4     USA 2009-01-06
4 4.00 0.00  foo5     USA 2009-01-07

In [60]:
# tip 4
# change column names
dftest = pandas.util.testing.makeMixedDataFrame()
dftest
dftest.rename(columns={'A':'ID', 'D':'Date'})

    ID    B     C       Date
0 0.00 0.00  foo1 2009-01-01
1 1.00 1.00  foo2 2009-01-02
2 2.00 0.00  foo3 2009-01-05
3 3.00 1.00  foo4 2009-01-06
4 4.00 0.00  foo5 2009-01-07

In [61]:
# tip 5
# duplicate a column
dftest = pandas.util.testing.makeMixedDataFrame()
dftest['E'] = dftest['C']
dftest

     A    B     C          D     E
0 0.00 0.00  foo1 2009-01-01  foo1
1 1.00 1.00  foo2 2009-01-02  foo2
2 2.00 0.00  foo3 2009-01-05  foo3
3 3.00 1.00  foo4 2009-01-06  foo4
4 4.00 0.00  foo5 2009-01-07  foo5

In [62]:
# tip 6
# determine dataframe datatypes
dftest = pandas.util.testing.makeMixedDataFrame()
dataTypeSeries = dftest.dtypes
print(dataTypeSeries)

A           float64
B           float64
C            object
D    datetime64[ns]
dtype: object

In [63]:
# tip 7
# delete a dataframe column

# df = df.drop('column_name', 1)
# where 1 is the axis number (0 for rows and 1 for columns.)

# To delete the column without having to reassign df you can do:
# df.drop('column_name', axis=1, inplace=True)

# To drop by column number instead of by column label, try this to delete, e.g. the 1st, 2nd and 4th columns:
# df = df.drop(df.columns[[0, 1, 3]], axis=1)  
# df.columns is zero-based pd.Index 

# Working with "text" syntax for the columns:
# df.drop(['column_nameA', 'column_nameB'], axis=1, inplace=True)

dftest = pandas.util.testing.makeMixedDataFrame()
print(dftest)
dftest = dftest.drop('C', 1)
print(dftest)

     A    B     C          D
0 0.00 0.00  foo1 2009-01-01
1 1.00 1.00  foo2 2009-01-02
2 2.00 0.00  foo3 2009-01-05
3 3.00 1.00  foo4 2009-01-06
4 4.00 0.00  foo5 2009-01-07
     A    B          D
0 0.00 0.00 2009-01-01
1 1.00 1.00 2009-01-02
2 2.00 0.00 2009-01-05
3 3.00 1.00 2009-01-06
4 4.00 0.00 2009-01-07

In [64]:
# tip 8
# reorder columns (flipflop column a and column d)
dftest = pandas.util.testing.makeMixedDataFrame()
print(dftest)
dftest = dftest[['D','B','C','A']]
print(dftest)

     A    B     C          D
0 0.00 0.00  foo1 2009-01-01
1 1.00 1.00  foo2 2009-01-02
2 2.00 0.00  foo3 2009-01-05
3 3.00 1.00  foo4 2009-01-06
4 4.00 0.00  foo5 2009-01-07
           D    B     C    A
0 2009-01-01 0.00  foo1 0.00
1 2009-01-02 1.00  foo2 1.00
2 2009-01-05 0.00  foo3 2.00
3 2009-01-06 1.00  foo4 3.00
4 2009-01-07 0.00  foo5 4.00

In [65]:
df.head(3)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,SR,OptYr,tpid_length
0,"SCHNEIDER, LAURA E",2020-07-14,Standby Only - COVID-19,0111,999,13976.00.01.0111.999,0.00,0.00,0.00,SR-0000000,OY.,20
1,"SCHNEIDER, LAURA E",2020-07-17,Standby Only - COVID-19,0111,999,13976.00.01.0111.999,0.00,0.00,0.00,SR-0000000,OY.,20
2,"SCHNEIDER, LAURA E",2020-07-20,Standby Only - COVID-19,0111,999,13976.00.01.0111.999,8.00,0.00,8.00,SR-0000000,OY.,20

In [66]:
# delete tpid_length column
df = df.drop('tpid_length', 1)
df.head(3)

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total,SR,OptYr
0,"SCHNEIDER, LAURA E",2020-07-14,Standby Only - COVID-19,0111,999,13976.00.01.0111.999,0.00,0.00,0.00,SR-0000000,OY.
1,"SCHNEIDER, LAURA E",2020-07-17,Standby Only - COVID-19,0111,999,13976.00.01.0111.999,0.00,0.00,0.00,SR-0000000,OY.
2,"SCHNEIDER, LAURA E",2020-07-20,Standby Only - COVID-19,0111,999,13976.00.01.0111.999,8.00,0.00,8.00,SR-0000000,OY.

In [67]:
df.to_excel (r'U:\AP2 Regular & OT Hours for Adv by CCC_#505ap-modified.xlsx', index = False, header=True)

In [49]:
import datetime
#oy1
d1s = datetime.date(2010,8,3)
d1e = datetime.date(2011,8,2) 
print('oy1', d1s, d1e)
df[(df['Work Date'] >= d1s) & (df['Work Date'] <= d1e)]

oy1 2010-08-03 2011-08-02

NameError: name 'df' is not defined

In [228]:
#oy2
d2s = datetime.date(2011,8,3)
d2e = datetime.date(2012,8,2) 
print('oy2', d2s, d2e)
df[(df['Work Date'] >= d2s) & (df['Work Date'] <= d2e)]

oy2 2011-08-03 2012-08-02

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total]
Index: []

In [229]:
#oy3
d3s = datetime.date(2012,8,3)
d3e = datetime.date(2013,8,2) 
print('oy3', d3s, d3e)
df[(df['Work Date'] >= d3s) & (df['Work Date'] <= d3e)]

oy3 2012-08-03 2013-08-02

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total]
Index: []

In [230]:
#oy4
d4s = datetime.date(2013,8,3)
d4e = datetime.date(2014,8,2) 
print('oy4', d4s, d4e)
df[(df['Work Date'] >= d4s) & (df['Work Date'] <= d4e)]

oy4 2013-08-03 2014-08-02

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total]
Index: []

In [231]:
#oy5
d5s = datetime.date(2014,8,3)
d5e = datetime.date(2015,8,2) 
print('oy5', d5s, d5e)
df[(df['Work Date'] >= d5s) & (df['Work Date'] <= d5e)]

oy5 2014-08-03 2015-08-02

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total]
Index: []

In [232]:
#oy6
d6s = datetime.date(2015,8,3)
d6e = datetime.date(2016,8,2) 
print('oy6', d6s, d6e)
df[(df['Work Date'] >= d6s) & (df['Work Date'] <= d6e)]

oy6 2015-08-03 2016-08-02

Empty DataFrame
Columns: [User, Work Date, Description, CLIN, WBS, TPID, Straight, Overtime, Total]
Index: []

In [233]:
#oy7
d7s = datetime.date(2016,8,3)
d7e = datetime.date(2017,8,2) 
print('oy7', d7s, d7e)
df[(df['Work Date'] >= d7s) & (df['Work Date'] <= d7e)]

oy7 2016-08-03 2017-08-02

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
56,"THOMPSON, MORRIS R",2017-07-11,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00
57,"THOMPSON, MORRIS R",2017-07-18,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00
58,"THOMPSON, MORRIS R",2017-08-01,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
127,"THOMPSON, MORRIS R",2017-07-17,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00
128,"THOMPSON, MORRIS R",2017-07-19,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
129,"THOMPSON, MORRIS R",2017-07-20,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00
190,"THOMPSON, MORRIS R",2017-07-13,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00
256,"THOMPSON, MORRIS R",2017-07-12,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00
257,"THOMPSON, MORRIS R",2017-07-27,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
330,"THOMPSON, MORRIS R",2017-07-21,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
397,"THOMPSON, MORRIS R",2017-07-14,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,8.00,0.00,8.00
398,"THOMPSON, MORRIS R",2017-07-20,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
399,"THOMPSON, MORRIS R",2017-07-25,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
400,"THOMPSON, MORRIS R",2017-07-26,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
401,"THOMPSON, MORRIS R",2017-08-02,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
477,"THOMPSON, MORRIS R",2017-07-10,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
478,"THOMPSON, MORRIS R",2017-07-28,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
875,"LOVELACE, TAMEKA N",2017-03-20,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00
876,"LOVELACE, TAMEKA N",2017-03-22,Site L,7900,000,1SAP2.C.7900.000,0.00,4.00,4.00
877,"LOVELACE, TAMEKA N",2017-03-23,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00
878,"LOVELACE, TAMEKA N",2017-04-05,Site L,7900,000,1SAP2.C.7900.000,0.00,4.00,4.00
879,"LOVELACE, TAMEKA N",2017-04-10,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00
880,"LOVELACE, TAMEKA N",2017-04-19,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00
881,"LOVELACE, TAMEKA N",2017-05-04,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00
882,"LOVELACE, TAMEKA N",2017-05-09,Site L,7900,000,1SAP2.C.7900.000,4.00,0.00,4.00
883,"LOVELACE, TAMEKA N",2017-05-12,Site L,7900,000,1SAP2.C.7900.000,0.00,4.00,4.00
884,"LOVELACE, TAMEKA N",2017-05-24,Site L,7900,000,1SAP2.C.7900.000,0.00,4.00,4.00
...,...,...,...,...,...,...,...,...,...
595820,"Simmons, Kenneth",2017-05-02,D Mission Support,7300,683,1SAP2.C.7300.683,9.00,0.00,9.00
595821,"Simmons, Kenneth",2017-05-09,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00
595822,"Simmons, Kenneth",2017-05-18,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00
595823,"Simmons, Kenneth",2017-06-27,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50
595824,"Simmons, Kenneth",2017-06-28,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00
595825,"Simmons, Kenneth",2017-07-03,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50
595826,"Simmons, Kenneth",2017-07-05,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00
595827,"Simmons, Kenneth",2017-07-08,D Mission Support,7300,683,1SAP2.C.7300.683,4.50,0.00,4.50
595828,"Simmons, Kenneth",2017-03-29,D Mission Support,7300,683,1SAP2.C.7300.683,7.50,0.00,7.50
595829,"Simmons, Kenneth",2017-04-06,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00
595830,"Simmons, Kenneth",2017-04-19,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50
595831,"Simmons, Kenneth",2017-04-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00
595832,"Simmons, Kenneth",2017-04-26,D Mission Support,7300,683,1SAP2.C.7300.683,9.50,0.00,9.50
595833,"Simmons, Kenneth",2017-05-05,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00
595834,"Simmons, Kenneth",2017-05-24,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00
595835,"Simmons, Kenneth",2017-05-31,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50
595836,"Simmons, Kenneth",2017-06-06,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50
595837,"Simmons, Kenneth",2017-06-18,D Mission Support,7300,683,1SAP2.C.7300.683,13.00,0.00,13.00
595838,"Simmons, Kenneth",2017-06-21,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00
595839,"Simmons, Kenneth",2017-07-10,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00
595840,"Simmons, Kenneth",2017-07-13,D Mission Support,7300,683,1SAP2.C.7300.683,3.50,0.00,3.50
595841,"Simmons, Kenneth",2017-03-20,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00
595842,"Simmons, Kenneth",2017-03-23,D Mission Support,7300,683,1SAP2.C.7300.683,8.00,0.00,8.00
595843,"Simmons, Kenneth",2017-03-27,D Mission Support,7300,683,1SAP2.C.7300.683,7.00,0.00,7.00
595844,"Simmons, Kenneth",2017-04-17,D Mission Support,7300,683,1SAP2.C.7300.683,6.00,0.00,6.00
595845,"Simmons, Kenneth",2017-05-07,D Mission Support,7300,683,1SAP2.C.7300.683,14.00,0.00,14.00
595846,"Simmons, Kenneth",2017-05-10,D Mission Support,7300,683,1SAP2.C.7300.683,11.50,0.00,11.50
595847,"Simmons, Kenneth",2017-06-13,D Mission Support,7300,683,1SAP2.C.7300.683,8.50,0.00,8.50
595848,"Simmons, Kenneth",2017-07-06,D Mission Support,7300,683,1SAP2.C.7300.683,12.00,0.00,12.00
595849,"Simmons, Kenneth",2017-07-19,D Mission Support,7300,683,1SAP2.C.7300.683,5.50,0.00,5.50

In [234]:
#oy8
d8s = datetime.date(2017,8,3)
d8e = datetime.date(2018,8,2) 
print('oy8', d8s, d8e)
df[(df['Work Date'] >= d8s) & (df['Work Date'] <= d8e)]

oy8 2017-08-03 2018-08-02

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total
3,"THOMPSON, MORRIS R",2017-08-10,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
4,"THOMPSON, MORRIS R",2017-08-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
5,"THOMPSON, MORRIS R",2017-09-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
6,"THOMPSON, MORRIS R",2017-09-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
7,"THOMPSON, MORRIS R",2017-09-21,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
8,"THOMPSON, MORRIS R",2017-09-25,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
9,"THOMPSON, MORRIS R",2017-10-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
10,"THOMPSON, MORRIS R",2017-10-27,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
11,"THOMPSON, MORRIS R",2017-10-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
12,"THOMPSON, MORRIS R",2017-11-02,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
13,"THOMPSON, MORRIS R",2017-11-07,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
14,"THOMPSON, MORRIS R",2017-11-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
15,"THOMPSON, MORRIS R",2017-11-17,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
16,"THOMPSON, MORRIS R",2017-11-20,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
17,"THOMPSON, MORRIS R",2017-11-28,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
18,"THOMPSON, MORRIS R",2017-11-29,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
19,"THOMPSON, MORRIS R",2017-12-08,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
20,"THOMPSON, MORRIS R",2018-01-16,Asset Management,8400,514,1SAP2.C.8400.514,4.00,0.00,4.00
21,"THOMPSON, MORRIS R",2018-01-30,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
22,"THOMPSON, MORRIS R",2018-02-12,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
23,"THOMPSON, MORRIS R",2018-02-20,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00
24,"THOMPSON, MORRIS R",2018-02-23,Asset Management,8400,514,1SAP2.C.8400.514,-8.00,0.00,-8.00
25,"THOMPSON, MORRIS R",2018-02-23,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00
26,"THOMPSON, MORRIS R",2018-03-05,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
27,"THOMPSON, MORRIS R",2018-03-06,Asset Management,8400,514,1SAP2.C.8400.514,8.00,0.00,8.00
28,"THOMPSON, MORRIS R",2018-03-07,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00
29,"THOMPSON, MORRIS R",2018-03-16,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00
30,"THOMPSON, MORRIS R",2018-03-23,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,7.50,0.00,7.50
31,"THOMPSON, MORRIS R",2018-03-27,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00
32,"THOMPSON, MORRIS R",2018-05-16,Asset Mgmt (Local),8440,514,1SAP2.C.8440.514,8.00,0.00,8.00
...,...,...,...,...,...,...,...,...,...
595662,"Holbrook, Michael",2017-08-29,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00
595663,"Holbrook, Michael",2017-09-01,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00
595664,"Holbrook, Michael",2017-09-04,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00
595665,"Holbrook, Michael",2017-09-06,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00
595666,"Holbrook, Michael",2017-09-07,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595667,"Holbrook, Michael",2017-09-14,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00
595668,"Holbrook, Michael",2017-10-03,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595669,"Holbrook, Michael",2017-10-04,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595670,"Holbrook, Michael",2017-10-06,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,5.00,0.00,5.00
595671,"Holbrook, Michael",2017-10-17,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595672,"Holbrook, Michael",2017-10-26,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595673,"Holbrook, Michael",2017-11-09,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595683,"Holbrook, Michael",2017-08-11,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,7.00,0.00,7.00
595684,"Holbrook, Michael",2017-08-21,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595685,"Holbrook, Michael",2017-08-28,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00
595686,"Holbrook, Michael",2017-08-31,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00
595687,"Holbrook, Michael",2017-09-05,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00
595688,"Holbrook, Michael",2017-09-21,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595689,"Holbrook, Michael",2017-10-02,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.50,0.00,8.50
595690,"Holbrook, Michael",2017-10-11,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,9.00,0.00,9.00
595691,"Holbrook, Michael",2017-11-03,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,7.00,0.00,7.00
595692,"Holbrook, Michael",2017-11-07,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595693,"Holbrook, Michael",2017-11-15,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595707,"Holbrook, Michael",2017-08-03,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,10.00,0.00,10.00
595708,"Holbrook, Michael",2017-08-15,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,14.50,0.00,14.50
595709,"Holbrook, Michael",2017-09-11,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595710,"Holbrook, Michael",2017-09-13,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,0.00,0.00,0.00
595711,"Holbrook, Michael",2017-09-26,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,7.00,0.00,7.00
595712,"Holbrook, Michael",2017-10-13,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00
595713,"Holbrook, Michael",2017-10-23,TIER 3 TEAM,8330,000,1SAP2.F.8330.000.TIER003,8.00,0.00,8.00

In [235]:
#oy9
d9s = datetime.date(2018,8,3)
d9e = datetime.date(2019,8,2) 
print('oy9', d9s, d9e)
df[(df['Work Date'] >= d9s) & (df['Work Date'] <= d9e)]

oy9 2018-08-03 2019-08-02

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total
35,"THOMPSON, MORRIS R",2018-08-06,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
36,"THOMPSON, MORRIS R",2018-08-20,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50
37,"THOMPSON, MORRIS R",2018-08-22,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
38,"THOMPSON, MORRIS R",2018-08-30,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
39,"THOMPSON, MORRIS R",2018-09-06,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
40,"THOMPSON, MORRIS R",2018-09-26,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
41,"THOMPSON, MORRIS R",2018-10-10,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
42,"THOMPSON, MORRIS R",2018-10-15,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
43,"THOMPSON, MORRIS R",2019-01-07,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
44,"THOMPSON, MORRIS R",2019-02-22,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
45,"THOMPSON, MORRIS R",2019-03-18,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50
46,"THOMPSON, MORRIS R",2019-03-26,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50
47,"THOMPSON, MORRIS R",2019-04-18,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50
48,"THOMPSON, MORRIS R",2019-04-22,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50
49,"THOMPSON, MORRIS R",2019-05-10,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,6.00,0.00,6.00
50,"THOMPSON, MORRIS R",2019-05-20,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.50,0.00,8.50
51,"THOMPSON, MORRIS R",2019-06-07,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,5.50,0.00,5.50
52,"THOMPSON, MORRIS R",2019-06-20,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,9.00,0.00,9.00
53,"THOMPSON, MORRIS R",2019-06-26,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,9.00,0.00,9.00
54,"THOMPSON, MORRIS R",2019-07-15,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,9.00,0.00,9.00
55,"THOMPSON, MORRIS R",2019-07-23,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,9.00,0.00,9.00
100,"THOMPSON, MORRIS R",2018-08-21,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
101,"THOMPSON, MORRIS R",2018-09-17,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,9.50,0.00,9.50
102,"THOMPSON, MORRIS R",2018-09-18,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
103,"THOMPSON, MORRIS R",2018-10-25,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
104,"THOMPSON, MORRIS R",2018-11-15,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
105,"THOMPSON, MORRIS R",2018-11-30,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,7.00,0.00,7.00
106,"THOMPSON, MORRIS R",2018-12-10,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
107,"THOMPSON, MORRIS R",2018-12-27,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,8.00,0.00,8.00
108,"THOMPSON, MORRIS R",2019-01-11,Asset Mgmt (Local),9440,514,1SAP2.C.9440.514,7.00,0.00,7.00
...,...,...,...,...,...,...,...,...,...
595349,"Stokes, Duane",2019-02-28,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,11.00,0.00,11.00
595350,"Stokes, Duane",2019-03-04,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00
595351,"Stokes, Duane",2019-03-18,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,9.50,0.00,9.50
595352,"Stokes, Duane",2019-04-18,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,13.00,0.00,13.00
595353,"Stokes, Duane",2019-05-03,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00
595354,"Stokes, Duane",2019-06-13,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,11.50,0.00,11.50
595355,"Stokes, Duane",2019-06-24,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00
595356,"Stokes, Duane",2019-07-16,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00
595357,"Stokes, Duane",2019-07-23,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,12.50,0.00,12.50
595358,"Stokes, Duane",2019-07-29,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,7.00,0.00,7.00
595359,"Stokes, Duane",2019-08-01,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,9.00,0.00,9.00
595396,"Stokes, Duane",2018-08-23,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00
595397,"Stokes, Duane",2018-10-02,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,9.50,0.00,9.50
595398,"Stokes, Duane",2018-10-09,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,12.00,0.00,12.00
595399,"Stokes, Duane",2018-10-26,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,8.00,0.00,8.00
595400,"Stokes, Duane",2018-12-07,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,7.00,0.00,7.00
595401,"Stokes, Duane",2018-12-11,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,7.50,0.00,7.50
595402,"Stokes, Duane",2018-12-21,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,11.00,0.00,11.00
595403,"Stokes, Duane",2019-02-12,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,11.00,0.00,11.00
595404,"Stokes, Duane",2019-02-14,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,8.00,0.00,8.00
595405,"Stokes, Duane",2019-04-24,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,13.00,0.00,13.00
595406,"Stokes, Duane",2019-05-20,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,4.50,0.00,4.50
595407,"Stokes, Duane",2019-05-31,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,12.00,0.00,12.00
595408,"Stokes, Duane",2019-06-04,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,8.00,0.00,8.00
595409,"Stokes, Duane",2019-06-11,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,9.00,0.00,9.00
595410,"Stokes, Duane",2019-06-17,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00
595411,"Stokes, Duane",2019-07-02,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,11.00,0.00,11.00
595412,"Stokes, Duane",2019-07-04,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,0.00,0.00,0.00
595413,"Stokes, Duane",2019-07-08,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,7.00,0.00,7.00
595414,"Stokes, Duane",2019-07-30,MLM,9330,000,1SAP2.F.9330.000.NMTMLMX,10.00,0.00,10.00

In [236]:
d_ext_start = datetime.date(2019,8,3)
print('oy.', d_ext_start)
df[df['Work Date'] >= d_ext_start]

oy. 2019-08-03

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total
1119,"LOVELACE, TAMEKA N",2019-08-06,Site L,9900,000,1SAP2.C.9900.000,0.00,0.00,0.00
1811,"LOVELACE, TAMEKA N",2019-08-05,Site L,9900,000,1SAP2.C.9900.000,0.00,0.00,0.00
11276,"TIMMONS, CARL A",2019-08-08,FS Installer,9420,000,1SAP2.P.9420.000.4926393,-4.00,0.00,-4.00
11477,"TIMMONS, CARL A",2019-08-08,FS Installer,9420,000,1SAP2.P.9420.000.4926393,4.00,0.00,4.00
11584,"TIMMONS, CARL A",2019-08-12,FS Installer,9420,000,1SAP2.P.9420.000.5364379,0.00,0.00,0.00
31417,"SHINGLES, VELGAMON C",2019-08-06,FS Installer,9420,000,1SAP2.P.9420.000.5259260,0.00,0.00,0.00
31614,"SHINGLES, VELGAMON C",2019-08-05,FS Installer,9420,000,1SAP2.P.9420.000.5259260,0.00,0.00,0.00
31754,"SHINGLES, VELGAMON C",2019-08-07,FS Installer,9420,000,1SAP2.P.9420.000.5259260,0.00,0.00,0.00
36700,"MAYS, BERNADETTE",2019-08-19,Switch Tech (Local),9440,225,1SAP2.C.9440.225,0.00,0.00,0.00
47470,"MULLINS, JAMES D",2019-08-07,FS Installer,9420,000,1SAP2.P.9420.000.5473263,0.00,0.00,0.00
47670,"MULLINS, JAMES D",2019-08-07,FS Installer,9420,000,1SAP2.P.9420.000.5257101,0.00,0.00,0.00
47742,"MULLINS, JAMES D",2019-08-06,FS Installer,9420,000,1SAP2.P.9420.000.5473263,0.00,0.00,0.00
47743,"MULLINS, JAMES D",2019-08-08,FS Installer,9420,000,1SAP2.P.9420.000.5257101,0.00,0.00,0.00
47859,"MULLINS, JAMES D",2019-08-09,FS Installer,9420,000,1SAP2.P.9420.000.5257101,0.00,0.00,0.00
47916,"MULLINS, JAMES D",2019-08-05,FS Installer,9420,000,1SAP2.P.9420.000.5257101,0.00,0.00,0.00
68445,"BUCKMON, JOSEPH",2019-09-04,CD&D (Local),9440,215,1SAP2.C.9440.215,0.00,0.00,0.00
70200,"JONES, BILLIE H",2019-08-12,Proj Mgmt (Local),9440,415,1SAP2.C.9440.415,0.00,0.00,0.00
74071,"MAY, PORTIAH A",2019-08-05,PMO CLIN 9105,9105,000,1SAP2.C.9105.000,0.00,0.00,0.00
75715,"MAY, PORTIAH A",2019-08-05,PMO CLIN 9103,9103,000,1SAP2.C.9103.000,0.00,0.00,0.00
75986,"MAY, PORTIAH A",2019-08-05,PMO CLIN 9104,9104,000,1SAP2.C.9104.000,0.00,0.00,0.00
89221,"EDWARDS, REGINA",2019-08-07,Telephony,9400,517,1SAP2.C.9400.517,0.00,0.00,0.00
89375,"EDWARDS, REGINA",2019-08-08,Telephony,9400,517,1SAP2.C.9400.517,0.00,0.00,0.00
89432,"EDWARDS, REGINA",2019-08-06,Telephony,9400,517,1SAP2.C.9400.517,0.00,0.00,0.00
89433,"EDWARDS, REGINA",2019-08-09,Telephony,9400,517,1SAP2.C.9400.517,0.00,0.00,0.00
102593,"PERKINS, WILLIAM F",2019-10-15,Installer (Local),9440,815,1SAP2.C.9440.815,0.00,0.00,0.00
106559,"DEHN, ALBERT W",2019-08-05,FS Installer,9420,000,1SAP2.P.9420.000.4926393,8.00,0.00,8.00
106645,"DEHN, ALBERT W",2019-08-12,FS Installer,9420,000,1SAP2.P.9420.000.5364379,-8.00,0.00,-8.00
106808,"DEHN, ALBERT W",2019-08-07,FS Installer,9420,000,1SAP2.P.9420.000.4926393,8.00,0.00,8.00
106809,"DEHN, ALBERT W",2019-08-12,FS Installer,9420,000,1SAP2.P.9420.000.5364379,8.00,0.00,8.00
106903,"DEHN, ALBERT W",2019-08-05,FS Installer,9420,000,1SAP2.P.9420.000.4926393,-8.00,0.00,-8.00
...,...,...,...,...,...,...,...,...,...
544982,"Parker, Derrick",2019-08-08,FS Installer,9420,000,1SAP2.P.9420.000.4926393,-4.00,0.00,-4.00
545010,"Parker, Derrick",2019-08-09,FS Installer,9420,000,1SAP2.P.9420.000.4926393,-8.00,0.00,-8.00
545601,"Bellamy, Willie",2019-08-05,FS Installer,9420,000,1SAP2.P.9420.000.5066612,0.00,0.00,0.00
546861,"Sabur, Ali",2019-10-30,FS Installer,9420,000,1SAP2.P.9420.000.5066612,10.00,0.00,10.00
546862,"Sabur, Ali",2019-10-21,FS Installer,9420,000,1SAP2.P.9420.000.5328120,10.00,0.00,10.00
546863,"Sabur, Ali",2019-10-31,FS Installer,9420,000,1SAP2.P.9420.000.5066612,0.00,0.00,0.00
546864,"Sabur, Ali",2019-10-17,FS Installer,9420,000,1SAP2.P.9420.000.5328120,-10.00,0.00,-10.00
546865,"Sabur, Ali",2019-10-29,FS Installer,9420,000,1SAP2.P.9420.000.5066612,4.00,0.00,4.00
546866,"Sabur, Ali",2019-10-31,FS Installer,9420,000,1SAP2.P.9420.000.5066612,10.00,0.00,10.00
546867,"Sabur, Ali",2019-11-04,FS Installer,9420,000,1SAP2.P.9420.000.5066612,8.00,0.00,8.00
546868,"Sabur, Ali",2019-10-21,FS Installer,9420,000,1SAP2.P.9420.000.5328120,-10.00,0.00,-10.00
546869,"Sabur, Ali",2019-11-04,FS Installer,9420,000,1SAP2.P.9420.000.5066612,-8.00,0.00,-8.00
546870,"Sabur, Ali",2019-10-29,FS Installer,9420,000,1SAP2.P.9420.000.5066612,-4.00,0.00,-4.00
546871,"Sabur, Ali",2019-10-31,FS Installer,9420,000,1SAP2.P.9420.000.5066612,-10.00,0.00,-10.00
546872,"Sabur, Ali",2019-10-17,FS Installer,9420,000,1SAP2.P.9420.000.5328120,10.00,0.00,10.00
546873,"Sabur, Ali",2019-10-30,FS Installer,9420,000,1SAP2.P.9420.000.5066612,-10.00,0.00,-10.00
546874,"Johnson, Emile",2020-06-24,SIT,8440,238,1SAP2.C.8440.238.4247059,1.00,0.00,1.00
551247,"Bencivenga, Thomas",2019-08-19,Voice O&M Support,9500,619,1SAP2.C.9500.619.4464845,0.00,0.00,0.00
563327,"Crewe, Thomas",2019-09-17,CD&D/BOM Survey,9440,218,1SAP2.C.9440.218.5375908,0.00,0.00,0.00
564555,"Key, Larry",2019-08-06,Switch Tech,9440,228,1SAP2.C.9440.228.3722235,0.00,0.00,0.00
564831,"Key, Larry",2019-08-03,Switch Tech,9440,228,1SAP2.C.9440.228.3722235,0.00,0.00,0.00
564923,"Key, Larry",2019-08-05,Switch Tech,9440,228,1SAP2.C.9440.228.3722235,0.00,0.00,0.00
593592,"Tucker, Richard",2019-10-28,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00
593593,"Tucker, Richard",2019-12-02,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00
593685,"Tucker, Richard",2019-12-02,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00
593847,"Tucker, Richard",2019-12-03,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00
593935,"Tucker, Richard",2019-10-29,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00
593936,"Tucker, Richard",2019-10-30,1SAP2.C.9440.818.4831450,9440,818,1SAP2.C.9440.818.4831450,0.00,0.00,0.00
594023,"Tucker, Richard",2019-08-13,AMX Programmer,9440,328,1SAP2.C.9440.328.4697933,0.00,0.00,0.00
594102,"Tucker, Richard",2019-08-12,AMX Programmer (Local),9440,325,1SAP2.C.9440.325,0.00,0.00,0.00

,User,Work Date,Description,CLIN,WBS,TPID,Straight,Overtime,Total
0,"THOMPSON, MORRIS R",2017-07-21,Unbillable L&P,UNBL,000,1SAP2.X.UNBL.000.LPUNBLL,0.00,0.00,0.00
1,"THOMPSON, MORRIS R",2017-07-24,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00
2,"THOMPSON, MORRIS R",2017-07-31,Asset Management,7400,514,1SAP2.C.7400.514,8.00,0.00,8.00

In [42]:
df.head(3)

NameError: name 'df' is not defined