In [537]:
# chavez & coombs
# 2020-07-16
# cognos_data_management(v1.3).ipynb
# this script takes jacobs-cognos-output data and transforms its format to make it compatible with the deltek spreadsheet

In [538]:
# import module(s)
import pandas
import os

In [539]:
# current working directory
print(os.getcwd())

\\ain2\dfsroot\userdata48\willitc0\Data

In [540]:
# read data (from U:\ drive)
# cognos data downloaded as excel, which is then saved as a csv file
df = pandas.read_csv("U:\AP2 Regular & OT Hours for Adv by CCC_#505ap.csv")

C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (1,7,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [541]:
# format data
# round floating numbers to two decimal places in python pandas 
pandas.options.display.float_format = '{:.2f}'.format

In [542]:
# metadata
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214837 entries, 0 to 214836
Data columns (total 23 columns):
User                 214837 non-null object
User Id              214837 non-null object
Work Date            214837 non-null object
Month                214837 non-null object
Description          214837 non-null object
REF ID               214837 non-null int64
CLIN                 214837 non-null object
WBS                  38761 non-null object
TASK                 214837 non-null object
TPID                 214837 non-null object
ProjNo               214837 non-null object
WB2                  214837 non-null object
Project Id           214837 non-null object
Pay Type             214837 non-null object
Corporation          214837 non-null object
Company Name         214837 non-null object
Approver             214837 non-null object
Status               214837 non-null object
Straight             214837 non-null float64
Overtime             214837 non-null float64
Total                214837 non-null float64
Date Time Entered    214837 non-null object
Org Id               214837 non-null object
dtypes: float64(3), int64(1), object(19)
memory usage: 37.7+ MB

In [543]:
# data snapshot
df.head(3)

,User,User Id,Work Date,Month,Description,REF ID,CLIN,WBS,TASK,TPID,...,Pay Type,Corporation,Company Name,Approver,Status,Straight,Overtime,Total,Date Time Entered,Org Id
0,"SCHNEIDER, LAURA E",10036,"Jul 15, 2020","Jul 15, 2020",Standby Only - COVID-19,13976,.01.,NaN,999,13976.00.01.0111.999,...,R,FNS,FNS,S-MELISSA RONEY-DEMA,Signed,0.00,0.00,0.00,"Jul 17, 2020 6:28:04 AM",1.01.01.01
1,"SCHNEIDER, LAURA E",10036,"Jul 13, 2020","Jul 13, 2020",Software Services,13976,.01.,NaN,509,13976.00.01.0111.509,...,R,FNS,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,"Jul 17, 2020 7:37:51 AM",1.01.01.01
2,"SCHNEIDER, LAURA E",10036,"Jul 16, 2020","Jul 16, 2020",Software Services,13976,.01.,NaN,509,13976.00.01.0111.509,...,R,FNS,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,"Jul 17, 2020 7:37:51 AM",1.01.01.01

In [544]:
# add ChangeID
df['ChangeID'] = df['ProjNo']
df.head(3)

,User,User Id,Work Date,Month,Description,REF ID,CLIN,WBS,TASK,TPID,...,Corporation,Company Name,Approver,Status,Straight,Overtime,Total,Date Time Entered,Org Id,ChangeID
0,"SCHNEIDER, LAURA E",10036,"Jul 15, 2020","Jul 15, 2020",Standby Only - COVID-19,13976,.01.,NaN,999,13976.00.01.0111.999,...,FNS,FNS,S-MELISSA RONEY-DEMA,Signed,0.00,0.00,0.00,"Jul 17, 2020 6:28:04 AM",1.01.01.01,0
1,"SCHNEIDER, LAURA E",10036,"Jul 13, 2020","Jul 13, 2020",Software Services,13976,.01.,NaN,509,13976.00.01.0111.509,...,FNS,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,"Jul 17, 2020 7:37:51 AM",1.01.01.01,0
2,"SCHNEIDER, LAURA E",10036,"Jul 16, 2020","Jul 16, 2020",Software Services,13976,.01.,NaN,509,13976.00.01.0111.509,...,FNS,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,"Jul 17, 2020 7:37:51 AM",1.01.01.01,0

In [545]:
# add option year
df.insert(24, 'OptYr', 'OY.')
df.head(3)

,User,User Id,Work Date,Month,Description,REF ID,CLIN,WBS,TASK,TPID,...,Company Name,Approver,Status,Straight,Overtime,Total,Date Time Entered,Org Id,ChangeID,OptYr
0,"SCHNEIDER, LAURA E",10036,"Jul 15, 2020","Jul 15, 2020",Standby Only - COVID-19,13976,.01.,NaN,999,13976.00.01.0111.999,...,FNS,S-MELISSA RONEY-DEMA,Signed,0.00,0.00,0.00,"Jul 17, 2020 6:28:04 AM",1.01.01.01,0,OY.
1,"SCHNEIDER, LAURA E",10036,"Jul 13, 2020","Jul 13, 2020",Software Services,13976,.01.,NaN,509,13976.00.01.0111.509,...,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,"Jul 17, 2020 7:37:51 AM",1.01.01.01,0,OY.
2,"SCHNEIDER, LAURA E",10036,"Jul 16, 2020","Jul 16, 2020",Software Services,13976,.01.,NaN,509,13976.00.01.0111.509,...,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,"Jul 17, 2020 7:37:51 AM",1.01.01.01,0,OY.

In [546]:
# check data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214837 entries, 0 to 214836
Data columns (total 25 columns):
User                 214837 non-null object
User Id              214837 non-null object
Work Date            214837 non-null object
Month                214837 non-null object
Description          214837 non-null object
REF ID               214837 non-null int64
CLIN                 214837 non-null object
WBS                  38761 non-null object
TASK                 214837 non-null object
TPID                 214837 non-null object
ProjNo               214837 non-null object
WB2                  214837 non-null object
Project Id           214837 non-null object
Pay Type             214837 non-null object
Corporation          214837 non-null object
Company Name         214837 non-null object
Approver             214837 non-null object
Status               214837 non-null object
Straight             214837 non-null float64
Overtime             214837 non-null float64
Total                214837 non-null float64
Date Time Entered    214837 non-null object
Org Id               214837 non-null object
ChangeID             214837 non-null object
OptYr                214837 non-null object
dtypes: float64(3), int64(1), object(21)
memory usage: 41.0+ MB

In [547]:
# column A
df['User'].head(3)

0    SCHNEIDER, LAURA E
1    SCHNEIDER, LAURA E
2    SCHNEIDER, LAURA E
Name: User, dtype: object

In [548]:
# column B
df['User Id'].head(3)

0    10036
1    10036
2    10036
Name: User Id, dtype: object

In [549]:
# column C
# modify workdate format
df['Work Date'] = pandas.to_datetime(df['Work Date']).dt.strftime('%Y-%m-%d')
df['Work Date'].head(3)

0    2020-07-15
1    2020-07-13
2    2020-07-16
Name: Work Date, dtype: object

In [550]:
# column D
# modify month format
df['Month'] = pandas.to_datetime(df['Month']).dt.strftime('%Y-%m')
df['Month'].head(3)

0    2020-07
1    2020-07
2    2020-07
Name: Month, dtype: object

In [551]:
# column E
df['Description'].head(3)

0    Standby Only - COVID-19
1          Software Services
2          Software Services
Name: Description, dtype: object

In [552]:
# column F
df['REF ID'].head(3)

0    13976
1    13976
2    13976
Name: REF ID, dtype: int64

In [553]:
# Check TPID format
df['TPID'].head(3)

0    13976.00.01.0111.999
1    13976.00.01.0111.509
2    13976.00.01.0111.509
Name: TPID, dtype: object

In [554]:
# column G
# get clin from tpid
df['CLIN'] = df.TPID.str.split(".", expand=True,)[3]
df['CLIN'].head(3)

0    0111
1    0111
2    0111
Name: CLIN, dtype: object

In [555]:
# column H
# get wbs from tpid
df['WBS'] = df.TPID.str.split(".", expand=True,)[4]
df['WBS'].head(3)

0    999
1    509
2    509
Name: WBS, dtype: object

In [556]:
# column I
df['TPID'].head(3)

0    13976.00.01.0111.999
1    13976.00.01.0111.509
2    13976.00.01.0111.509
Name: TPID, dtype: object

In [557]:
# column J
df['TASK'].head(3)

0    999
1    509
2    509
Name: TASK, dtype: object

In [558]:
# column K
df['Pay Type'].head(3)

0    R
1    R
2    R
Name: Pay Type, dtype: object

In [559]:
# column L
df['Corporation'].head(3)

0    FNS
1    FNS
2    FNS
Name: Corporation, dtype: object

In [560]:
# column M
df['Company Name'].head(3)

0    FNS
1    FNS
2    FNS
Name: Company Name, dtype: object

In [561]:
# column N
df['Approver'].head(3)

0    S-MELISSA RONEY-DEMA
1    S-MELISSA RONEY-DEMA
2    S-MELISSA RONEY-DEMA
Name: Approver, dtype: object

In [562]:
# column O
df['Status'].head(3)

0    Signed
1    Signed
2    Signed
Name: Status, dtype: object

In [563]:
# column P
df['Straight'].head(3)
df['Straight'].describe()

count   214837.00
mean         5.73
std          3.75
min        -20.00
25%          2.50
50%          8.00
75%          8.00
max         40.00
Name: Straight, dtype: float64

In [564]:
# column Q
df['Overtime'].head(3)
df['Overtime'].describe()

count   214837.00
mean         0.15
std          1.14
min        -12.50
25%          0.00
50%          0.00
75%          0.00
max         16.00
Name: Overtime, dtype: float64

In [565]:
# column R
df['Total'].head(3)
df['Total'].describe()

count   214837.00
mean         5.88
std          3.70
min        -20.00
25%          3.00
50%          8.00
75%          8.00
max         40.00
Name: Total, dtype: float64

In [566]:
# column S (modify format)
df['Date Time Entered'] = pandas.to_datetime(df['Date Time Entered']).dt.strftime('%Y-%m-%d %h:%m:%s')
df['Date Time Entered'].head(3)

0    2020-07-17 06:28:04
1    2020-07-17 07:37:51
2    2020-07-17 07:37:51
Name: Date Time Entered, dtype: object

In [567]:
# column T
df['Org Id'].head(3)

0    1.01.01.01
1    1.01.01.01
2    1.01.01.01
Name: Org Id, dtype: object

In [568]:
# column U
df['ChangeID'].head(3)

0    0
1    0
2    0
Name: ChangeID, dtype: object

In [569]:
# column V
# Opt Yr
df['OptYr'].head(3)

0    OY.
1    OY.
2    OY.
Name: OptYr, dtype: object

In [570]:
# check data format
df

,User,User Id,Work Date,Month,Description,REF ID,CLIN,WBS,TASK,TPID,...,Company Name,Approver,Status,Straight,Overtime,Total,Date Time Entered,Org Id,ChangeID,OptYr
0,"SCHNEIDER, LAURA E",10036,2020-07-15,2020-07,Standby Only - COVID-19,13976,0111,999,999,13976.00.01.0111.999,...,FNS,S-MELISSA RONEY-DEMA,Signed,0.00,0.00,0.00,2020-07-17 06:28:04,1.01.01.01,0,OY.
1,"SCHNEIDER, LAURA E",10036,2020-07-13,2020-07,Software Services,13976,0111,509,509,13976.00.01.0111.509,...,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,2020-07-17 07:37:51,1.01.01.01,0,OY.
2,"SCHNEIDER, LAURA E",10036,2020-07-16,2020-07,Software Services,13976,0111,509,509,13976.00.01.0111.509,...,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,2020-07-17 07:37:51,1.01.01.01,0,OY.
3,"SCHNEIDER, LAURA E",10036,2020-07-14,2020-07,Standby Only - COVID-19,13976,0111,999,999,13976.00.01.0111.999,...,FNS,S-MELISSA RONEY-DEMA,Signed,0.00,0.00,0.00,2020-07-17 06:28:04,1.01.01.01,0,OY.
4,"SCHNEIDER, LAURA E",10036,2020-07-17,2020-07,Standby Only - COVID-19,13976,0111,999,999,13976.00.01.0111.999,...,FNS,S-MELISSA RONEY-DEMA,Signed,0.00,0.00,0.00,2020-07-17 06:28:04,1.01.01.01,0,OY.
5,"SCHNEIDER, LAURA E",10036,2020-07-15,2020-07,Software Services,13976,0111,509,509,13976.00.01.0111.509,...,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,2020-07-17 07:37:51,1.01.01.01,0,OY.
6,"SCHNEIDER, LAURA E",10036,2020-07-16,2020-07,Standby Only - COVID-19,13976,0111,999,999,13976.00.01.0111.999,...,FNS,S-MELISSA RONEY-DEMA,Signed,0.00,0.00,0.00,2020-07-17 06:28:04,1.01.01.01,0,OY.
7,"SCHNEIDER, LAURA E",10036,2020-07-13,2020-07,Standby Only - COVID-19,13976,0111,999,999,13976.00.01.0111.999,...,FNS,S-MELISSA RONEY-DEMA,Signed,0.00,0.00,0.00,2020-07-17 06:28:04,1.01.01.01,0,OY.
8,"SCHNEIDER, LAURA E",10036,2020-07-14,2020-07,Software Services,13976,0111,509,509,13976.00.01.0111.509,...,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,2020-07-17 07:37:51,1.01.01.01,0,OY.
9,"SCHNEIDER, LAURA E",10036,2020-07-17,2020-07,Software Services,13976,0111,509,509,13976.00.01.0111.509,...,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,2020-07-17 07:37:51,1.01.01.01,0,OY.
10,"THOMPSON, MORRIS R",51288,2019-08-06,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.00,0.00,9.00,2019-08-06 14:09:27,1.01.01.01,0,OY.
11,"THOMPSON, MORRIS R",51288,2019-08-08,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.00,0.00,9.00,2019-08-08 15:07:03,1.01.01.01,0,OY.
12,"THOMPSON, MORRIS R",51288,2019-08-26,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.00,0.00,9.00,2019-08-26 14:33:38,1.01.01.01,0,OY.
13,"THOMPSON, MORRIS R",51288,2019-08-27,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.00,0.00,9.00,2019-08-27 13:59:25,1.01.01.01,0,OY.
14,"THOMPSON, MORRIS R",51288,2019-08-30,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,4.00,0.00,4.00,2019-08-29 14:50:59,1.01.01.01,0,OY.
15,"THOMPSON, MORRIS R",51288,2019-09-16,2019-09,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.50,0.00,9.50,2019-09-16 14:29:42,1.01.01.01,0,OY.
16,"THOMPSON, MORRIS R",51288,2019-09-23,2019-09,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.00,0.00,9.00,2019-09-23 14:43:34,1.01.01.01,0,OY.
17,"THOMPSON, MORRIS R",51288,2019-10-11,2019-10,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,4.00,0.00,4.00,2019-10-09 14:21:48,1.01.01.01,0,OY.
18,"THOMPSON, MORRIS R",51288,2019-10-16,2019-10,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.50,0.00,9.50,2019-10-16 15:00:07,1.01.01.01,0,OY.
19,"THOMPSON, MORRIS R",51288,2019-08-12,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,8.50,0.00,8.50,2019-08-12 13:50:07,1.01.01.01,0,OY.
20,"THOMPSON, MORRIS R",51288,2019-08-16,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,3.50,0.00,3.50,2019-08-15 14:42:32,1.01.01.01,0,OY.
21,"THOMPSON, MORRIS R",51288,2019-08-22,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.50,0.00,9.50,2019-08-22 15:38:00,1.01.01.01,0,OY.
22,"THOMPSON, MORRIS R",51288,2019-09-18,2019-09,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.00,0.00,9.00,2019-09-18 14:42:26,1.01.01.01,0,OY.
23,"THOMPSON, MORRIS R",51288,2019-09-20,2019-09,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,3.50,0.00,3.50,2019-09-19 14:24:25,1.01.01.01,0,OY.
24,"THOMPSON, MORRIS R",51288,2019-09-30,2019-09,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.00,0.00,9.00,2019-09-30 14:27:13,1.01.01.01,0,OY.
25,"THOMPSON, MORRIS R",51288,2019-10-04,2019-10,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,4.00,0.00,4.00,2019-10-03 14:37:46,1.01.01.01,0,OY.
26,"THOMPSON, MORRIS R",51288,2019-10-08,2019-10,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.00,0.00,9.00,2019-10-08 14:26:20,1.01.01.01,0,OY.
27,"THOMPSON, MORRIS R",51288,2019-08-14,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.00,0.00,9.00,2019-08-14 14:27:43,1.01.01.01,0,OY.
28,"THOMPSON, MORRIS R",51288,2019-08-23,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,6.50,0.00,6.50,2019-08-22 15:38:00,1.01.01.01,0,OY.
29,"THOMPSON, MORRIS R",51288,2019-08-28,2019-08,Asset Mgmt,13976,0016,514,514,13976.00.00.0016.514,...,FNS,S-VAN LUONG,Processed,9.00,0.00,9.00,2019-08-28 14:39:48,1.01.01.01,0,OY.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214807,"Stokes, Duane",Z608998,2019-08-27,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,6.50,0.00,6.50,2019-08-28 14:42:20,1.01.01.01,CHG00000000,OY.
214808,"Stokes, Duane",Z608998,2019-09-12,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,11.50,0.00,11.50,2019-09-12 19:20:19,1.01.01.01,CHG00000000,OY.
214809,"Stokes, Duane",Z608998,2019-09-18,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,7.00,0.00,7.00,2019-09-18 20:57:31,1.01.01.01,CHG00000000,OY.
214810,"Stokes, Duane",Z608998,2019-10-02,2019-10,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,2.00,0.00,2.00,2019-10-03 12:24:32,1.01.01.01,CHG00000000,OY.
214811,"Stokes, Duane",Z608998,2019-10-09,2019-10,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,10.50,0.00,10.50,2019-10-09 22:44:18,1.01.01.01,CHG00000000,OY.
214812,"Stokes, Duane",Z608998,2019-08-13,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,9.00,0.00,9.00,2019-08-13 17:25:27,1.01.01.01,CHG00000000,OY.
214813,"Stokes, Duane",Z608998,2019-08-20,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,9.00,0.00,9.00,2019-08-20 14:39:20,1.01.01.01,CHG00000000,OY.
214814,"Stokes, Duane",Z608998,2019-08-21,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,10.00,0.00,10.00,2019-08-21 18:28:57,1.01.01.01,CHG00000000,OY.
214815,"Stokes, Duane",Z608998,2019-09-24,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,11.50,0.00,11.50,2019-09-24 19:27:50,1.01.01.01,CHG00000000,OY.
214816,"Stokes, Duane",Z608998,2019-10-01,2019-10,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,1.50,0.00,1.50,2019-10-03 12:24:32,1.01.01.01,CHG00000000,OY.
214817,"Stokes, Duane",Z608998,2019-10-07,2019-10,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,8.50,0.00,8.50,2019-10-07 21:59:13,1.01.01.01,CHG00000000,OY.
214818,"Stokes, Duane",Z608998,2019-10-08,2019-10,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,5.50,0.00,5.50,2019-10-09 14:56:28,1.01.01.01,CHG00000000,OY.
214819,"Stokes, Duane",Z608998,2019-08-05,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,7.00,0.00,7.00,2019-08-07 15:10:12,1.01.01.01,CHG00000000,OY.
214820,"Stokes, Duane",Z608998,2019-08-28,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,9.00,0.00,9.00,2019-08-28 14:42:20,1.01.01.01,CHG00000000,OY.
214821,"Stokes, Duane",Z608998,2019-09-09,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,9.00,0.00,9.00,2019-09-10 16:54:29,1.01.01.01,CHG00000000,OY.
214822,"Stokes, Duane",Z608998,2019-09-20,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,7.00,0.00,7.00,2019-09-20 11:47:54,1.01.01.01,CHG00000000,OY.
214823,"Stokes, Duane",Z608998,2019-08-07,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,7.50,0.00,7.50,2019-08-07 16:38:26,1.01.01.01,CHG00000000,OY.
214824,"Stokes, Duane",Z608998,2019-08-30,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,10.00,0.00,10.00,2019-08-30 15:15:54,1.01.01.01,CHG00000000,OY.
214825,"Stokes, Duane",Z608998,2019-08-12,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,9.00,0.00,9.00,2019-08-13 17:25:27,1.01.01.01,CHG00000000,OY.
214826,"Stokes, Duane",Z608998,2019-08-14,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,9.50,0.00,9.50,2019-08-19 11:26:55,1.01.01.01,CHG00000000,OY.
214827,"Stokes, Duane",Z608998,2019-08-29,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,10.50,0.00,10.50,2019-08-29 19:19:02,1.01.01.01,CHG00000000,OY.
214828,"Stokes, Duane",Z608998,2019-09-10,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,9.50,0.00,9.50,2019-09-10 16:54:29,1.01.01.01,CHG00000000,OY.
214829,"Stokes, Duane",Z608998,2019-09-17,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,11.00,0.00,11.00,2019-09-17 16:55:10,1.01.01.01,CHG00000000,OY.
214830,"Stokes, Duane",Z608998,2019-09-19,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,7.00,0.00,7.00,2019-09-19 16:00:00,1.01.01.01,CHG00000000,OY.
214831,"Stokes, Duane",Z608998,2019-09-25,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,9.00,0.00,9.00,2019-09-25 14:56:09,1.01.01.01,CHG00000000,OY.
214832,"Stokes, Duane",Z608998,2019-09-27,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,11.00,0.00,11.00,2019-09-27 16:10:08,1.01.01.01,CHG00000000,OY.
214833,"Stokes, Duane",Z608998,2019-08-22,2019-08,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,4.00,0.00,4.00,2019-08-22 09:05:14,1.01.01.01,CHG00000000,OY.
214834,"Stokes, Duane",Z608998,2019-09-04,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,8.00,0.00,8.00,2019-09-05 19:12:26,1.01.01.01,CHG00000000,OY.
214835,"Stokes, Duane",Z608998,2019-09-30,2019-09,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,9.00,0.00,9.00,2019-10-01 14:54:41,1.01.01.01,CHG00000000,OY.
214836,"Stokes, Duane",Z608998,2019-10-03,2019-10,O&M Support,13976,0007,000,000,13976.00.00.0007.000,...,SUB-HTS INFOSYS,S-WILLIAM WHITE,Processed,9.00,0.00,9.00,2019-10-04 15:00:26,1.01.01.01,CHG00000000,OY.

In [571]:
# write data to csv (default is U:\Documents)
df.to_csv('AP2 Regular & OT Hours for Adv by CCC_#505ap-modified.csv')

In [572]:
# check metadata
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214837 entries, 0 to 214836
Data columns (total 25 columns):
User                 214837 non-null object
User Id              214837 non-null object
Work Date            214837 non-null object
Month                214837 non-null object
Description          214837 non-null object
REF ID               214837 non-null int64
CLIN                 214837 non-null object
WBS                  214837 non-null object
TASK                 214837 non-null object
TPID                 214837 non-null object
ProjNo               214837 non-null object
WB2                  214837 non-null object
Project Id           214837 non-null object
Pay Type             214837 non-null object
Corporation          214837 non-null object
Company Name         214837 non-null object
Approver             214837 non-null object
Status               214837 non-null object
Straight             214837 non-null float64
Overtime             214837 non-null float64
Total                214837 non-null float64
Date Time Entered    214837 non-null object
Org Id               214837 non-null object
ChangeID             214837 non-null object
OptYr                214837 non-null object
dtypes: float64(3), int64(1), object(21)
memory usage: 41.0+ MB

In [573]:
# data check
df.head(3)

,User,User Id,Work Date,Month,Description,REF ID,CLIN,WBS,TASK,TPID,...,Company Name,Approver,Status,Straight,Overtime,Total,Date Time Entered,Org Id,ChangeID,OptYr
0,"SCHNEIDER, LAURA E",10036,2020-07-15,2020-07,Standby Only - COVID-19,13976,0111,999,999,13976.00.01.0111.999,...,FNS,S-MELISSA RONEY-DEMA,Signed,0.00,0.00,0.00,2020-07-17 06:28:04,1.01.01.01,0,OY.
1,"SCHNEIDER, LAURA E",10036,2020-07-13,2020-07,Software Services,13976,0111,509,509,13976.00.01.0111.509,...,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,2020-07-17 07:37:51,1.01.01.01,0,OY.
2,"SCHNEIDER, LAURA E",10036,2020-07-16,2020-07,Software Services,13976,0111,509,509,13976.00.01.0111.509,...,FNS,S-MELISSA RONEY-DEMA,Signed,8.00,0.00,8.00,2020-07-17 07:37:51,1.01.01.01,0,OY.

In [574]:
# tip 1
# create dataframe with mixed data types
pandas.util.testing.makeMixedDataFrame()

     A    B     C          D
0 0.00 0.00  foo1 2009-01-01
1 1.00 1.00  foo2 2009-01-02
2 2.00 0.00  foo3 2009-01-05
3 3.00 1.00  foo4 2009-01-06
4 4.00 0.00  foo5 2009-01-07

In [575]:
# tip 2
# insert a new column which is a function of another column
dftest = pandas.util.testing.makeMixedDataFrame()
#print(dftest)
dftest.insert(3, 'A2', dftest['A'] * 2)
dftest

     A    B     C   A2          D
0 0.00 0.00  foo1 0.00 2009-01-01
1 1.00 1.00  foo2 2.00 2009-01-02
2 2.00 0.00  foo3 4.00 2009-01-05
3 3.00 1.00  foo4 6.00 2009-01-06
4 4.00 0.00  foo5 8.00 2009-01-07

In [576]:
# tip 3
# insert a new column with a constant value in the column with index 3 (i.e., 4)
dftest = pandas.util.testing.makeMixedDataFrame()
dftest.insert(3, 'Country', 'USA')
dftest

     A    B     C Country          D
0 0.00 0.00  foo1     USA 2009-01-01
1 1.00 1.00  foo2     USA 2009-01-02
2 2.00 0.00  foo3     USA 2009-01-05
3 3.00 1.00  foo4     USA 2009-01-06
4 4.00 0.00  foo5     USA 2009-01-07

In [577]:
# tip 4
# change column names
dftest = pandas.util.testing.makeMixedDataFrame()
dftest
dftest.rename(columns={'A':'ID', 'D':'Date'})

    ID    B     C       Date
0 0.00 0.00  foo1 2009-01-01
1 1.00 1.00  foo2 2009-01-02
2 2.00 0.00  foo3 2009-01-05
3 3.00 1.00  foo4 2009-01-06
4 4.00 0.00  foo5 2009-01-07

In [578]:
# tip 5
# duplicate a column
dftest = pandas.util.testing.makeMixedDataFrame()
dftest['E'] = dftest['C']
dftest

     A    B     C          D     E
0 0.00 0.00  foo1 2009-01-01  foo1
1 1.00 1.00  foo2 2009-01-02  foo2
2 2.00 0.00  foo3 2009-01-05  foo3
3 3.00 1.00  foo4 2009-01-06  foo4
4 4.00 0.00  foo5 2009-01-07  foo5

In [579]:
# tip 6
# determine dataframe datatypes
dftest = pandas.util.testing.makeMixedDataFrame()
dataTypeSeries = dftest.dtypes
print(dataTypeSeries)

A           float64
B           float64
C            object
D    datetime64[ns]
dtype: object

In [580]:
# tip 7
# delete a dataframe column

# df = df.drop('column_name', 1)
# where 1 is the axis number (0 for rows and 1 for columns.)

# To delete the column without having to reassign df you can do:
# df.drop('column_name', axis=1, inplace=True)

# To drop by column number instead of by column label, try this to delete, e.g. the 1st, 2nd and 4th columns:
# df = df.drop(df.columns[[0, 1, 3]], axis=1)  
# df.columns is zero-based pd.Index 

# Working with "text" syntax for the columns:
# df.drop(['column_nameA', 'column_nameB'], axis=1, inplace=True)

dftest = pandas.util.testing.makeMixedDataFrame()
print(dftest)
dftest = dftest.drop('C', 1)
print(dftest)

     A    B     C          D
0 0.00 0.00  foo1 2009-01-01
1 1.00 1.00  foo2 2009-01-02
2 2.00 0.00  foo3 2009-01-05
3 3.00 1.00  foo4 2009-01-06
4 4.00 0.00  foo5 2009-01-07
     A    B          D
0 0.00 0.00 2009-01-01
1 1.00 1.00 2009-01-02
2 2.00 0.00 2009-01-05
3 3.00 1.00 2009-01-06
4 4.00 0.00 2009-01-07